(function(){
  Object.assign(state,{
    warehouses:[],movements:[],notifications:[],dictionaryGroups:[],dictionaryItems:[],
    settings:[],materialCategories:[],brands:[],suppliers:[],activity:[],clientContacts:[],
    projectSites:[],payrollPeriods:[],payrollEntries:[],payrollAdjustments:[],
    payrollYear:new Date().getFullYear(),payrollMonth:new Date().getMonth()+1
  });
  Object.assign(pageMeta,{
    notifications:['Уведомления','Обновить'],payroll:['Зарплаты','Корректировка'],settings:['Настройки','Добавить значение']
  });

  const canPayroll=()=>['owner','admin','accountant'].includes(state.profile?.role);
  const canSettings=()=>['owner','admin'].includes(state.profile?.role);
  const canEmployees=()=>['owner','admin','accountant'].includes(state.profile?.role);
  const canManageEntity=t=>({
    client:['owner','admin','project_manager','marketing','accountant'],
    project:['owner','admin','project_manager','foreman'],
    task:['owner','admin','project_manager','foreman','employee'],
    expense:['owner','admin','accountant','project_manager'],
    material:['owner','admin','procurement','storekeeper'],
    employee:['owner','admin','accountant']
  }[t]||[]).includes(state.profile?.role);
  const localized=v=>typeof v==='object'&&v?v.ru||v.en||Object.values(v)[0]||'—':v||'—';
  const isoNow=()=>{const d=new Date();d.setMinutes(d.getMinutes()-d.getTimezoneOffset());return d.toISOString().slice(0,16)};
  const tableFor=t=>({client:'clients',project:'projects',task:'tasks',expense:'expenses',material:'materials',employee:'employees'}[t]);
  const movementName=t=>({receipt:'Приход',issue:'Выдача',reserve:'Резерв',unreserve:'Снять резерв',return:'Возврат',transfer:'Перемещение',writeoff:'Списание',defect:'Брак',inventory:'Инвентаризация'}[t]||t);
  const entityLabel=t=>({client:'клиента',project:'проект',task:'задачу',expense:'расход',material:'материал',employee:'сотрудника'}[t]||'запись');

  loadAll=async function(){
    const uid=state.session?.user?.id;
    const base=await Promise.all([
      safeLoad('/rest/v1/profiles?select=*&archived_at=is.null&order=full_name.asc'),
      safeLoad('/rest/v1/projects?select=*&deleted_at=is.null&archived_at=is.null&order=updated_at.desc'),
      safeLoad('/rest/v1/clients?select=*&deleted_at=is.null&archived_at=is.null&order=created_at.desc'),
      safeLoad('/rest/v1/tasks?select=*&deleted_at=is.null&archived_at=is.null&order=due_date.asc.nullslast'),
      safeLoad('/rest/v1/project_stages?select=*&order=sort_order.asc'),
      safeLoad('/rest/v1/materials?select=*&deleted_at=is.null&archived_at=is.null&order=name.asc'),
      safeLoad('/rest/v1/warehouse_stock?select=*'),
      safeLoad('/rest/v1/warehouse_locations?select=*&is_active=eq.true&order=name.asc'),
      safeLoad('/rest/v1/stock_movements?select=*&reversed_at=is.null&order=movement_date.desc&limit=100'),
      safeLoad('/rest/v1/dictionary_groups?select=*&order=code.asc'),
      safeLoad('/rest/v1/dictionary_items?select=*&order=sort_order.asc'),
      safeLoad('/rest/v1/app_settings?select=*'),
      safeLoad('/rest/v1/material_categories?select=*&order=sort_order.asc'),
      safeLoad('/rest/v1/material_brands?select=*&is_active=eq.true&order=name.asc'),
      safeLoad('/rest/v1/suppliers?select=*&is_active=eq.true&order=name.asc'),
      safeLoad('/rest/v1/client_contacts?select=*&deleted_at=is.null&order=created_at.desc'),
      safeLoad('/rest/v1/project_sites?select=*&archived_at=is.null&order=created_at.desc'),
      safeLoad(`/rest/v1/notifications?select=*&or=(recipient_id.is.null,recipient_id.eq.${uid})&order=created_at.desc&limit=100`)
    ]);
    [state.profiles,state.projects,state.clients,state.tasks,state.stages,state.materials,state.stock,state.warehouses,state.movements,state.dictionaryGroups,state.dictionaryItems,state.settings,state.materialCategories,state.brands,state.suppliers,state.clientContacts,state.projectSites,state.notifications]=base;
    state.profile=state.profiles.find(x=>x.id===uid)||{full_name:state.session?.user?.email,role:'employee'};
    if(canEmployees())state.employees=await safeLoad('/rest/v1/employees?select=*&deleted_at=is.null&archived_at=is.null&order=full_name.asc');else state.employees=[];
    if(canFinance()){
      [state.expenses,state.payments]=await Promise.all([
        safeLoad('/rest/v1/expenses?select=*&deleted_at=is.null&archived_at=is.null&order=expense_date.desc'),
        safeLoad('/rest/v1/payments?select=*&order=due_date.desc.nullslast')
      ]);
    }else{state.expenses=[];state.payments=[]}
    if(canPayroll()){
      [state.payrollPeriods,state.payrollEntries,state.payrollAdjustments,state.activity]=await Promise.all([
        safeLoad('/rest/v1/payroll_periods?select=*&order=period_year.desc,period_month.desc'),
        safeLoad('/rest/v1/payroll_entries?select=*&order=updated_at.desc'),
        safeLoad('/rest/v1/payroll_adjustments?select=*&order=adjustment_date.desc'),
        safeLoad('/rest/v1/activity_log?select=*&order=created_at.desc&limit=250')
      ]);
    }else{state.payrollPeriods=[];state.payrollEntries=[];state.payrollAdjustments=[];state.activity=[]}
    updateShell();await applyBranding();renderPage();
  };

  updateShell=function(){
    const name=state.profile?.full_name||state.session?.user?.email||'Space Buro',role=state.profile?.role;
    $('#userName').textContent=name;$('#userRole').textContent=roleName(role);$('#avatar').textContent=name.split(/\s+/).map(x=>x[0]).join('').slice(0,2).toUpperCase();
    $('#projectsCount').textContent=state.projects.length;$('#clientsCount').textContent=state.clients.length;$('#tasksCount').textContent=state.tasks.filter(t=>t.status!=='completed').length;
    const unread=state.notifications.filter(n=>!n.read_at).length;$('#notificationsCount').textContent=unread;$('#notificationsCount').classList.toggle('hidden',!unread);
    $$('.finance-nav').forEach(x=>x.classList.toggle('hidden',!canFinance()));$$('.payroll-nav').forEach(x=>x.classList.toggle('hidden',!canPayroll()));$$('.employee-nav').forEach(x=>x.classList.toggle('hidden',!canEmployees()));$$('.settings-nav').forEach(x=>x.classList.toggle('hidden',!canSettings()));
    const access={owner:null,admin:null,accountant:['dashboard','clients','projects','employees','expenses','payments','payroll','notifications'],project_manager:['dashboard','clients','projects','tasks','gantt','materials','warehouse','expenses','payments','notifications'],foreman:['dashboard','projects','tasks','gantt','materials','warehouse','notifications'],designer:['dashboard','projects','tasks','gantt','notifications'],procurement:['dashboard','projects','materials','warehouse','notifications'],storekeeper:['dashboard','projects','materials','warehouse','notifications'],marketing:['dashboard','clients','notifications'],employee:['dashboard','tasks','notifications']}[role];
    if(access)$$('.nav-btn[data-page]').forEach(x=>x.classList.toggle('hidden',!access.includes(x.dataset.page)));
  };

  setPage=function(page){
    if((page==='expenses'||page==='payments')&&!canFinance())page='dashboard';
    if(page==='payroll'&&!canPayroll())page='dashboard';if(page==='employees'&&!canEmployees())page='dashboard';if(page==='settings'&&!canSettings())page='dashboard';
    state.page=page;$$('.nav-btn').forEach(b=>b.classList.toggle('active',b.dataset.page===page));const meta=pageMeta[page]||pageMeta.dashboard;
    $('#pageTitle').textContent=meta[0];$('#breadcrumb').textContent='SPACE BURO / '+meta[0].toUpperCase();$('#pageAction').innerHTML=(page==='notifications'?'↻':'＋')+' <span>'+meta[1]+'</span>';
    $('#sidebar').classList.remove('open');$('#scrim').classList.remove('show');renderPage();
  };

  function brandSetting(){return state.settings.find(x=>x.setting_key==='branding')?.setting_value||{}}
  async function signedUrl(path){if(!path)return null;const data=await rawApi('/storage/v1/object/sign/company-files/'+path.split('/').map(encodeURIComponent).join('/'),{method:'POST',body:JSON.stringify({expiresIn:3600})});return data?.signedURL?SUPABASE_URL+data.signedURL:null}
  async function applyBranding(){
    const b=brandSetting(),img=$('#brandLogo'),fallback=$('#brandFallback');$('#brandName').textContent=b.brand_name||'SPACE BURO';
    let url=b.logo_url||null;if(b.logo_path)try{url=await signedUrl(b.logo_path)}catch{}
    if(url){img.src=url;img.classList.remove('hidden');fallback.classList.add('hidden')}else{img.classList.add('hidden');fallback.classList.remove('hidden')}
    if(b.favicon_url){let link=document.querySelector("link[rel='icon']")||document.createElement('link');link.rel='icon';link.href=b.favicon_url;document.head.appendChild(link)}
  }
  async function uploadObject(file,path){
    const res=await fetch(SUPABASE_URL+'/storage/v1/object/company-files/'+path.split('/').map(encodeURIComponent).join('/'),{method:'POST',headers:{apikey:SUPABASE_KEY,Authorization:'Bearer '+state.session.access_token,'Content-Type':file.type||'application/octet-stream','x-upsert':'true'},body:file});
    if(!res.ok){const e=await res.json().catch(()=>({}));throw new Error(e.message||'Не удалось загрузить файл')}return path;
  }
  async function saveSetting(key,value){const old=state.settings.find(x=>x.setting_key===key);if(old)return update('app_settings',old.id,{setting_value:value});const rows=await rawApi('/rest/v1/app_settings',{method:'POST',headers:{Prefer:'return=representation'},body:JSON.stringify({setting_key:key,setting_value:value})});return rows[0]}

  function actionBar(type,id){if(!canManageEntity(type))return '<div class="warning-box section-gap">Доступ только для просмотра. Изменения ограничены вашей ролью.</div>';const duplicate=type==='project'&&state.profile?.role==='foreman'?'':`<button class="btn" onclick="duplicateRecord('${type}','${id}')">⧉ Копировать</button>`;return `<div class="action-row"><button class="btn primary" onclick="editRecord('${type}','${id}')">✎ Изменить</button>${duplicate}<button class="btn" onclick="archiveRecord('${type}','${id}')">▣ В архив</button><button class="btn danger" onclick="deleteRecord('${type}','${id}')">Удалить</button></div>`}
  window.editRecord=(type,id)=>({client:openClientEdit,project:openProjectEdit,task:openTaskEdit,expense:openExpenseEdit,material:openMaterialEdit,employee:openEmployeeEdit}[type]?.(id));
  window.archiveRecord=async(type,id)=>{if(!confirm(`Переместить ${entityLabel(type)} в архив?`))return;await update(tableFor(type),id,{archived_at:new Date().toISOString()});$('#drawerOverlay').classList.remove('show');await loadAll();toast('Запись перемещена в архив')};
  window.deleteRecord=async(type,id)=>{if(!confirm(`Удалить ${entityLabel(type)}? Запись останется в истории изменений.`))return;await update(tableFor(type),id,{deleted_at:new Date().toISOString()});$('#drawerOverlay').classList.remove('show');await loadAll();toast('Запись удалена')};
  window.duplicateRecord=async(type,id)=>{
    let created;
    if(type==='project'){const p=state.projects.find(x=>x.id===id);created=await insert('projects',{number:p.number+'-COPY-'+String(Date.now()).slice(-4),name:p.name+' — копия',client_id:p.client_id,client:p.client,category:p.category,project_category:p.project_category,location:p.location,address:p.address,district:p.district,status:'Новый',progress:0,budget:p.budget,contract_amount:p.contract_amount,planned_expenses:p.planned_expenses,start_date:p.start_date,due_date:p.due_date,note:p.note,template_source_id:p.id})}
    if(type==='client'){const c=state.clients.find(x=>x.id===id);created=await insert('clients',{name:c.name+' — копия',company:c.company,phone:c.phone,whatsapp:c.whatsapp,email:c.email,address:c.address,area:c.area,client_type:c.client_type,source:c.source,notes:c.notes})}
    if(type==='task'){const t=state.tasks.find(x=>x.id===id);created=await insert('tasks',{title:t.title+' — копия',project_id:t.project_id,stage_id:t.stage_id,description:t.description,assignee_id:t.assignee_id,start_date:t.start_date,due_date:t.due_date,priority:t.priority,status:'new',progress:0,planned_hours:t.planned_hours,cost:t.cost,requires_verification:t.requires_verification,recurrence_rule:t.recurrence_rule})}
    if(type==='expense'){const x=state.expenses.find(x=>x.id===id);created=await insert('expenses',{project_id:x.project_id,stage_id:x.stage_id,category:x.category,subcategory:x.subcategory,description:x.description+' — копия',supplier_name:x.supplier_name,planned_amount:x.planned_amount,actual_amount:x.actual_amount,vat_amount:x.vat_amount,expense_date:new Date().toISOString().slice(0,10),status:x.status,payment_status:'unpaid',currency:x.currency,payment_method:x.payment_method,notes:x.notes})}
    if(type==='material'){const m=state.materials.find(x=>x.id===id);created=await insert('materials',{name:m.name+' — копия',code:(m.code||'MAT')+'-'+String(Date.now()).slice(-4),category_id:m.category_id,subcategory:m.subcategory,brand:m.brand,brand_id:m.brand_id,supplier_id:m.supplier_id,color:m.color,dimensions:m.dimensions,thickness:m.thickness,unit:m.unit,purchase_price:m.purchase_price,sale_price:m.sale_price,minimum_stock:m.minimum_stock,delivery_lead_days:m.delivery_lead_days,notes:m.notes})}
    if(type==='employee'){const e=state.employees.find(x=>x.id===id);created=await insert('employees',{full_name:e.full_name+' — копия',job_title:e.job_title,department:e.department,phone:e.phone,whatsapp:e.whatsapp,email:e.email,payment_type:e.payment_type,monthly_salary:e.monthly_salary,daily_rate:e.daily_rate,hourly_rate:e.hourly_rate,overtime_rate:e.overtime_rate,project_rate:e.project_rate,status:'working',notes:e.notes})}
    $('#drawerOverlay').classList.remove('show');await loadAll();toast(created?'Копия создана':'Не удалось создать копию');
  };

  function projectFields(p={}){return input('name','Название проекта','text',p.name||'','required')+input('number','Номер проекта','text',p.number||('SB-'+Date.now().toString().slice(-6)),'required')+select('client_id','Клиент','<option value="">Без клиента</option>'+optionList(state.clients,'id','name',p.client_id||''))+select('category','Тип проекта',['Мебельные проекты','Ремонт и fit-out','Строительные проекты','Сервисные и технические работы'].map(x=>`<option ${p.category===x?'selected':''}>${x}</option>`).join(''))+input('location','Локация','text',p.location||'Dubai')+input('district','Район','text',p.district||'')+input('address','Адрес','text',p.address||'')+select('manager_id','Менеджер проекта','<option value="">Не назначен</option>'+optionList(state.profiles,'id','full_name',p.manager_id||''))+select('foreman_id','Прораб','<option value="">Не назначен</option>'+optionList(state.profiles,'id','full_name',p.foreman_id||''))+select('designer_id','Дизайнер','<option value="">Не назначен</option>'+optionList(state.profiles,'id','full_name',p.designer_id||''))+input('start_date','Дата начала','date',p.start_date||'')+input('due_date','Плановый срок','date',p.due_date||'')+select('status','Статус',['Новый','Согласование','В работе','Монтаж','Завершён'].map(x=>`<option ${p.status===x?'selected':''}>${x}</option>`).join(''))+input('progress','Готовность, %','number',p.progress||0,'min="0" max="100"')+input('contract_amount','Договорная сумма, AED','number',p.contract_amount||p.budget||0)+input('planned_expenses','Плановые расходы, AED','number',p.planned_expenses||0)+'<label class="full">Комментарий<textarea name="note">'+esc(p.note||'')+'</textarea></label>'}
  function projectRecord(d){const c=state.clients.find(x=>x.id===d.client_id);return {...d,client_id:d.client_id||null,client:c?.name||null,manager_id:d.manager_id||null,foreman_id:d.foreman_id||null,designer_id:d.designer_id||null,start_date:d.start_date||null,due_date:d.due_date||null,progress:Math.min(100,Math.max(0,Number(d.progress)||0)),budget:Number(d.contract_amount||0),contract_amount:Number(d.contract_amount||0),planned_expenses:Number(d.planned_expenses||0)}}
  openProjectModal=function(){openModal('Новый проект',projectFields(),async d=>insert('projects',projectRecord(d)))};
  function openProjectEdit(id){const p=state.projects.find(x=>x.id===id);openModal('Изменить проект',projectFields(p),async d=>update('projects',id,projectRecord(d)))}

  function clientFields(c={}){return input('name','Имя клиента','text',c.name||'','required')+input('company','Компания','text',c.company||'')+input('phone','Телефон','text',c.phone||'')+input('whatsapp','WhatsApp','text',c.whatsapp||'')+input('email','Email','email',c.email||'')+input('address','Адрес','text',c.address||'')+input('area','Район','text',c.area||'')+select('client_type','Тип клиента',['Частный','Компания','Партнёр'].map(x=>`<option ${c.client_type===x?'selected':''}>${x}</option>`).join(''))+input('source','Источник','text',c.source||'')+'<label class="full">Комментарий<textarea name="notes">'+esc(c.notes||'')+'</textarea></label>'}
  openClientModal=function(){openModal('Новый клиент',clientFields(),async d=>insert('clients',d))};
  function openClientEdit(id){const c=state.clients.find(x=>x.id===id);openModal('Изменить клиента',clientFields(c),async d=>update('clients',id,d))}

  function taskFields(t={}){return input('title','Название задачи','text',t.title||'','required')+select('project_id','Проект','<option value="">Без проекта</option>'+optionList(state.projects,'id','name',t.project_id||''))+select('stage_id','Этап','<option value="">Без этапа</option>'+optionList(state.stages.filter(s=>!t.project_id||s.project_id===t.project_id),'id','name',t.stage_id||''))+select('assignee_id','Ответственный','<option value="">Не назначен</option>'+optionList(state.profiles,'id','full_name',t.assignee_id||''))+input('start_date','Дата начала','date',t.start_date||'')+input('due_date','Срок','date',t.due_date||'')+select('status','Статус',[['new','Новая'],['assigned','Назначена'],['in_progress','В работе'],['waiting_materials','Ожидает материалы'],['completed','Выполнена']].map(([v,n])=>`<option value="${v}" ${t.status===v?'selected':''}>${n}</option>`).join(''))+select('priority','Приоритет',[['low','Низкий'],['normal','Обычный'],['high','Высокий'],['critical','Критический']].map(([v,n])=>`<option value="${v}" ${t.priority===v?'selected':''}>${n}</option>`).join(''))+input('progress','Готовность, %','number',t.progress||0,'min="0" max="100"')+input('planned_hours','Плановые часы','number',t.planned_hours||0,'step="0.5"')+input('actual_hours','Фактические часы','number',t.actual_hours||0,'step="0.5"')+input('cost','Стоимость, AED','number',t.cost||0)+select('recurrence_rule','Повторение',`<option value="">Не повторять</option><option value="daily" ${t.recurrence_rule==='daily'?'selected':''}>Ежедневно</option><option value="weekly" ${t.recurrence_rule==='weekly'?'selected':''}>Еженедельно</option><option value="monthly" ${t.recurrence_rule==='monthly'?'selected':''}>Ежемесячно</option>`)+select('requires_verification','Проверка руководителем',`<option value="false" ${!t.requires_verification?'selected':''}>Не требуется</option><option value="true" ${t.requires_verification?'selected':''}>Требуется</option>`)+`<label class="full">Описание<textarea name="description">${esc(t.description||'')}</textarea></label>`}
  function taskRecord(d){return {...d,project_id:d.project_id||null,stage_id:d.stage_id||null,assignee_id:d.assignee_id||null,start_date:d.start_date||null,due_date:d.due_date||null,progress:Number(d.progress||0),planned_hours:Number(d.planned_hours||0),actual_hours:Number(d.actual_hours||0),cost:Number(d.cost||0),recurrence_rule:d.recurrence_rule||null,requires_verification:d.requires_verification==='true'}}
  openTaskModal=function(projectId=''){openModal('Новая задача',taskFields({project_id:projectId,status:'new',priority:'normal'}),async d=>insert('tasks',taskRecord(d)))};
  function openTaskEdit(id){const t=state.tasks.find(x=>x.id===id);openModal('Изменить задачу',taskFields(t),async d=>update('tasks',id,taskRecord(d)))}

  function expenseFields(x={}){return select('project_id','Проект','<option value="">Общий расход</option>'+optionList(state.projects,'id','name',x.project_id||''))+input('category','Категория','text',x.category||'Материалы','required')+input('subcategory','Подкатегория','text',x.subcategory||'')+input('description','Описание','text',x.description||'','required')+input('supplier_name','Поставщик','text',x.supplier_name||'')+input('planned_amount','План, AED','number',x.planned_amount||0)+input('actual_amount','Факт, AED','number',x.actual_amount||0,'required')+input('vat_amount','НДС, AED','number',x.vat_amount||0)+input('expense_date','Дата','date',x.expense_date||new Date().toISOString().slice(0,10))+select('payment_status', 'Статус оплаты',`<option value="unpaid" ${x.payment_status!=='paid'?'selected':''}>Не оплачено</option><option value="paid" ${x.payment_status==='paid'?'selected':''}>Оплачено</option>`)+input('payment_method','Способ оплаты','text',x.payment_method||'')+`<label class="full">Комментарий<textarea name="notes">${esc(x.notes||'')}</textarea></label>`}
  function expenseRecord(d){return {...d,project_id:d.project_id||null,planned_amount:Number(d.planned_amount||0),actual_amount:Number(d.actual_amount||0),vat_amount:Number(d.vat_amount||0),currency:'AED'}}
  openExpenseModal=function(){openModal('Новый расход',expenseFields(),async d=>insert('expenses',expenseRecord(d)))};
  function openExpenseEdit(id){const x=state.expenses.find(x=>x.id===id);openModal('Изменить расход',expenseFields(x),async d=>update('expenses',id,expenseRecord(d)))}

  function materialFields(m={}){return input('name','Название','text',m.name||'','required')+input('code','Код','text',m.code||'')+select('category_id','Категория','<option value="">Без категории</option>'+optionList(state.materialCategories,'id','name',m.category_id||''))+input('subcategory','Подкатегория','text',m.subcategory||'')+select('brand_id','Бренд','<option value="">Без бренда</option>'+optionList(state.brands,'id','name',m.brand_id||''))+select('supplier_id','Поставщик','<option value="">Без поставщика</option>'+optionList(state.suppliers,'id','name',m.supplier_id||''))+input('color','Цвет','text',m.color||'')+input('dimensions','Размер','text',m.dimensions||'')+input('thickness','Толщина, мм','number',m.thickness||'')+input('unit','Единица','text',m.unit||'pcs')+input('purchase_price','Закупочная цена','number',m.purchase_price||0)+input('sale_price','Цена продажи','number',m.sale_price||0)+input('minimum_stock','Минимальный остаток','number',m.minimum_stock||0)+input('minimum_order_quantity','Минимальный заказ','number',m.minimum_order_quantity||0)+input('delivery_lead_days','Срок доставки, дней','number',m.delivery_lead_days||0)+`<label class="full">Комментарий<textarea name="notes">${esc(m.notes||'')}</textarea></label>`}
  function materialRecord(d){const b=state.brands.find(x=>x.id===d.brand_id);return {...d,category_id:d.category_id||null,brand_id:d.brand_id||null,brand:b?.name||'',supplier_id:d.supplier_id||null,thickness:d.thickness?Number(d.thickness):null,purchase_price:Number(d.purchase_price||0),sale_price:Number(d.sale_price||0),minimum_stock:Number(d.minimum_stock||0),minimum_order_quantity:Number(d.minimum_order_quantity||0),delivery_lead_days:Number(d.delivery_lead_days||0)}}
  openMaterialModal=function(){openModal('Новый материал',materialFields(),async d=>insert('materials',materialRecord(d)))};
  function openMaterialEdit(id){const m=state.materials.find(x=>x.id===id);openModal('Изменить материал',materialFields(m),async d=>update('materials',id,materialRecord(d)))}

  function employeeFields(e={}){return input('full_name','Имя','text',e.full_name||'','required')+input('employee_number','Номер сотрудника','text',e.employee_number||'')+input('job_title','Должность','text',e.job_title||'')+input('department','Отдел','text',e.department||'')+input('phone','Телефон','text',e.phone||'')+input('whatsapp','WhatsApp','text',e.whatsapp||'')+input('email','Email','email',e.email||'')+input('start_date','Дата начала','date',e.start_date||'')+select('status', 'Статус',`<option value="working" ${e.status!=='vacation'&&e.status!=='dismissed'?'selected':''}>Работает</option><option value="vacation" ${e.status==='vacation'?'selected':''}>В отпуске</option><option value="dismissed" ${e.status==='dismissed'?'selected':''}>Уволен</option>`)+select('payment_type','Тип оплаты',[['monthly','Месячная'],['daily','Дневная'],['hourly','Почасовая'],['project','За проект']].map(([v,n])=>`<option value="${v}" ${e.payment_type===v?'selected':''}>${n}</option>`).join(''))+input('monthly_salary','Месячная зарплата','number',e.monthly_salary||0)+input('daily_rate','Дневная ставка','number',e.daily_rate||0)+input('hourly_rate','Почасовая ставка','number',e.hourly_rate||0)+input('overtime_rate','Overtime ставка','number',e.overtime_rate||0)+input('project_rate','Ставка за проект','number',e.project_rate||0)+`<label class="full">Комментарий<textarea name="notes">${esc(e.notes||'')}</textarea></label>`}
  function employeeRecord(d){return {...d,monthly_salary:Number(d.monthly_salary||0),daily_rate:Number(d.daily_rate||0),hourly_rate:Number(d.hourly_rate||0),overtime_rate:Number(d.overtime_rate||0),project_rate:Number(d.project_rate||0),start_date:d.start_date||null}}
  openEmployeeModal=function(){openModal('Новый сотрудник',employeeFields({payment_type:'monthly'}),async d=>insert('employees',employeeRecord(d)))};
  function openEmployeeEdit(id){const e=state.employees.find(x=>x.id===id);openModal('Изменить сотрудника',employeeFields(e),async d=>update('employees',id,employeeRecord(d)))}

  function drawer(title,number,subtitle,body){$('#drawerNumber').textContent=number||'';$('#drawerContent').innerHTML=`<h2 class="drawer-title">${esc(title)}</h2><p class="drawer-sub">${esc(subtitle||'')}</p>${body}`;$('#drawerOverlay').classList.add('show')}
  window.openClient=id=>{const c=state.clients.find(x=>x.id===id),projects=state.projects.filter(p=>p.client_id===id),contacts=state.clientContacts.filter(x=>x.client_id===id),sites=state.projectSites.filter(x=>x.client_id===id);drawer(c.name,c.client_number||'КЛИЕНТ',c.company||c.client_type,`<div class="detail-grid"><div class="detail-box"><span>Телефон</span><b>${esc(c.phone||'—')}</b></div><div class="detail-box"><span>WhatsApp</span><b>${esc(c.whatsapp||'—')}</b></div><div class="detail-box"><span>Email</span><b>${esc(c.email||'—')}</b></div><div class="detail-box"><span>Район</span><b>${esc(c.area||'—')}</b></div></div>${actionBar('client',id)}<div class="split-grid"><section><h3>Контакты</h3><div class="mini-list">${contacts.map(x=>`<div class="mini-item"><div><b>${esc(x.name)}</b><small>${esc(x.position||'')} · ${esc(x.phone||x.email||'')}</small></div></div>`).join('')||'<p class="muted">Дополнительных контактов нет.</p>'}</div><button class="btn section-gap" onclick="openClientContactModal('${id}')">＋ Контакт</button></section><section><h3>Объекты</h3><div class="mini-list">${sites.map(x=>`<div class="mini-item"><div><b>${esc(x.name)}</b><small>${esc(x.object_type||'Объект')} · ${esc(x.address||'')}</small></div></div>`).join('')||'<p class="muted">Объектов пока нет.</p>'}</div><button class="btn section-gap" onclick="openSiteModal('${id}')">＋ Объект</button></section></div><h3 class="section-gap">Проекты клиента</h3>${projectTable(projects)}`)};
  window.openClientContactModal=clientId=>openModal('Новый контакт',input('name','Имя','text','','required')+input('position','Должность')+input('phone','Телефон')+input('whatsapp','WhatsApp')+input('email','Email','email')+`<label class="full">Комментарий<textarea name="notes"></textarea></label>`,async d=>insert('client_contacts',{...d,client_id:clientId}));
  window.openSiteModal=clientId=>openModal('Новый объект',input('name','Название объекта','text','','required')+input('object_type','Тип объекта')+input('address','Адрес')+input('area','Район'),async d=>insert('project_sites',{...d,client_id:clientId}));

  window.openTask=id=>{const t=state.tasks.find(x=>x.id===id);drawer(t.title,'ЗАДАЧА',projectName(t.project_id),`<div class="detail-grid"><div class="detail-box"><span>Ответственный</span><b>${esc(employeeName(t.assignee_id))}</b></div><div class="detail-box"><span>Статус</span><b>${esc(taskStatus(t.status))}</b></div><div class="detail-box"><span>Срок</span><b>${date(t.due_date)}</b></div><div class="detail-box"><span>Готовность</span><b>${Number(t.progress)||0}%</b></div><div class="detail-box"><span>План / факт часов</span><b>${Number(t.planned_hours)||0} / ${Number(t.actual_hours)||0}</b></div><div class="detail-box"><span>Проверка</span><b>${t.requires_verification?(t.verified_at?'Подтверждена':'Требуется'):'Не требуется'}</b></div></div>${actionBar('task',id)}<h3>Описание</h3><p class="detail-note">${esc(t.description||'Описание не добавлено.')}</p>`)};
  window.openExpense=id=>{const x=state.expenses.find(x=>x.id===id);drawer(x.description,'РАСХОД',projectName(x.project_id),`<div class="detail-grid"><div class="detail-box"><span>Категория</span><b>${esc(x.category)}</b></div><div class="detail-box"><span>Дата</span><b>${date(x.expense_date)}</b></div><div class="detail-box"><span>План</span><b>${money(x.planned_amount)} AED</b></div><div class="detail-box"><span>Факт</span><b>${money(x.actual_amount)} AED</b></div><div class="detail-box"><span>Поставщик</span><b>${esc(x.supplier_name||'—')}</b></div><div class="detail-box"><span>Оплата</span><b>${esc(x.payment_status)}</b></div></div>${actionBar('expense',id)}<p class="detail-note">${esc(x.notes||'Комментариев нет.')}</p>`)};
  window.openMaterial=id=>{const m=state.materials.find(x=>x.id===id),s=state.stock.filter(x=>x.material_id===id),on=s.reduce((a,x)=>a+Number(x.quantity_on_hand||0),0),reserved=s.reduce((a,x)=>a+Number(x.reserved||0),0);drawer(m.name,m.code||'МАТЕРИАЛ',[m.brand,m.subcategory].filter(Boolean).join(' · '),`<div class="detail-grid"><div class="detail-box"><span>Остаток</span><b>${on} ${esc(m.unit)}</b></div><div class="detail-box"><span>Доступно</span><b>${on-reserved} ${esc(m.unit)}</b></div><div class="detail-box"><span>Закупка</span><b>${money(m.purchase_price)} AED</b></div><div class="detail-box"><span>Продажа</span><b>${money(m.sale_price)} AED</b></div><div class="detail-box"><span>Цвет / размер</span><b>${esc([m.color,m.dimensions].filter(Boolean).join(' · ')||'—')}</b></div><div class="detail-box"><span>Срок поставки</span><b>${Number(m.delivery_lead_days)||0} дней</b></div></div>${actionBar('material',id)}<p class="detail-note">${esc(m.notes||'Комментариев нет.')}</p>`)};
  window.openEmployee=id=>{const e=state.employees.find(x=>x.id===id),adj=state.payrollAdjustments.filter(x=>x.employee_id===id);drawer(e.full_name,e.employee_number||'СОТРУДНИК',`${e.job_title||'Сотрудник'} · ${e.department||'Без отдела'}`,`<div class="detail-grid"><div class="detail-box"><span>Статус</span><b>${esc(e.status||'working')}</b></div><div class="detail-box"><span>Тип оплаты</span><b>${esc(e.payment_type)}</b></div><div class="detail-box"><span>Месячная ставка</span><b>${money(e.monthly_salary)} AED</b></div><div class="detail-box"><span>Дневная ставка</span><b>${money(e.daily_rate)} AED</b></div><div class="detail-box"><span>Телефон</span><b>${esc(e.phone||'—')}</b></div><div class="detail-box"><span>Дата начала</span><b>${date(e.start_date)}</b></div></div>${actionBar('employee',id)}<h3>Последние начисления</h3><div class="mini-list">${adj.slice(0,8).map(a=>`<div class="mini-item"><div><b>${esc(a.adjustment_type)}</b><small>${date(a.adjustment_date)}</small></div><b>${money(a.amount)} AED</b></div>`).join('')||'<p class="muted">Начислений пока нет.</p>'}</div>`)};

  window.openProject=function(id,tab='overview'){
    const p=state.projects.find(x=>x.id===id);if(!p)return;const tasks=state.tasks.filter(x=>x.project_id===id),stages=state.stages.filter(x=>x.project_id===id),expenses=state.expenses.filter(x=>x.project_id===id),payments=state.payments.filter(x=>x.project_id===id),moves=state.movements.filter(x=>x.project_id===id),history=state.activity.filter(x=>x.entity_id===id&&(x.entity_type==='project'||x.entity_type==='projects'));
    const tabs=[['overview','Обзор'],['stages','Этапы'],['tasks','Задачи'],['gantt','Гант'],['finance','Финансы'],['materials','Материалы'],['history','История']];
    let body='';
    if(tab==='overview')body=`<div class="detail-grid"><div class="detail-box"><span>Тип проекта</span><b>${esc(p.category||'—')}</b></div><div class="detail-box"><span>Статус</span><b>${esc(p.status)}</b></div><div class="detail-box"><span>Готовность</span><b>${Number(p.progress)||0}%</b></div><div class="detail-box"><span>Плановый срок</span><b>${date(p.due_date)}</b></div><div class="detail-box"><span>Менеджер</span><b>${esc(employeeName(p.manager_id))}</b></div><div class="detail-box"><span>Прораб</span><b>${esc(employeeName(p.foreman_id))}</b></div><div class="detail-box"><span>Договорная сумма</span><b>${money(p.contract_amount||p.budget)} AED</b></div><div class="detail-box"><span>Плановые расходы</span><b>${money(p.planned_expenses)} AED</b></div></div><h3>Комментарий</h3><p class="detail-note">${esc(p.note||'Комментариев пока нет.')}</p>`;
    if(tab==='stages')body=`<div class="action-row"><button class="btn primary" onclick="openStageModal('${id}')">＋ Добавить этап</button></div><div class="mini-list">${stages.map(s=>`<div class="mini-item clickable" onclick="openStageModal('${id}','${s.id}')"><div><b>${esc(s.name)}</b><small>${date(s.start_date)} — ${date(s.end_date)} · ${esc(s.status)}</small></div><b>${Number(s.progress)||0}%</b></div>`).join('')||'<p class="muted">Этапов пока нет.</p>'}</div>`;
    if(tab==='tasks')body=`<div class="action-row"><button class="btn primary" onclick="openTaskModal('${id}')">＋ Добавить задачу</button></div>${taskTable(tasks)}`;
    if(tab==='gantt')body=tasks.some(t=>t.start_date&&t.due_date)?`<div class="warning-box">Общий Гант открыт на отдельной странице. Здесь показаны задачи только этого проекта.</div><div class="section-gap">${taskTable(tasks.filter(t=>t.start_date&&t.due_date))}</div>`:'<p class="muted">Добавьте задачам даты, чтобы построить график.</p>';
    if(tab==='finance'){const spent=expenses.reduce((a,x)=>a+Number(x.actual_amount||0),0),received=payments.filter(x=>x.status==='paid'&&x.direction==='income').reduce((a,x)=>a+Number(x.amount||0),0);body=`<div class="kpis">${kpi('AED','Договор',money(p.contract_amount||p.budget),'AED')}${kpi('↓','Получено',money(received),'AED')}${kpi('↑','Расходы',money(spent),'AED')}${kpi('%','Разница',money(received-spent),'AED')}</div><h3>Расходы</h3>${expenseTable(expenses)}`}
    if(tab==='materials')body=`<div class="action-row"><button class="btn primary" onclick="openWarehouseModal('${id}')">＋ Движение материала</button></div>${movementTable(moves)}`;
    if(tab==='history')body=`<div class="mini-list">${history.map(h=>`<div class="mini-item"><div><b>${esc(h.action)}</b><small>${date(h.created_at)} · ${esc(employeeName(h.actor_id))}</small></div></div>`).join('')||'<p class="muted">История изменений доступна руководителю и бухгалтеру.</p>'}</div>`;
    drawer(p.name,p.number,`${clientName(p.client_id,p.client)} · ${p.location||'—'}`,`<div class="tabs">${tabs.map(([v,n])=>`<button class="tab ${tab===v?'active':''}" onclick="openProject('${id}','${v}')">${n.toUpperCase()}</button>`).join('')}</div>${body}${actionBar('project',id)}`);
  };

  window.openStageModal=(projectId,stageId='')=>{const s=state.stages.find(x=>x.id===stageId)||{};openModal(stageId?'Изменить этап':'Новый этап',input('name','Название','text',s.name||'','required')+input('start_date','Дата начала','date',s.start_date||'')+input('end_date','Дата завершения','date',s.end_date||'')+select('status','Статус',['Не начат','В работе','Ожидает','Завершён'].map(x=>`<option ${s.status===x?'selected':''}>${x}</option>`).join(''))+input('progress','Готовность, %','number',s.progress||0,'min="0" max="100"')+select('responsible_user_id','Ответственный','<option value="">Не назначен</option>'+optionList(state.profiles,'id','full_name',s.responsible_user_id||''))+input('budget','Бюджет, AED','number',s.budget||0)+`<label class="full">Комментарий<textarea name="notes">${esc(s.notes||'')}</textarea></label>`,async d=>{const record={...d,project_id:projectId,start_date:d.start_date||null,end_date:d.end_date||null,responsible_user_id:d.responsible_user_id||null,progress:Number(d.progress||0),budget:Number(d.budget||0)};return stageId?update('project_stages',stageId,record):insert('project_stages',record)})};

  function expenseTable(list){return `<div class="table-wrap"><table class="data-table"><thead><tr><th>ОПИСАНИЕ</th><th>ПРОЕКТ</th><th>КАТЕГОРИЯ</th><th>ДАТА</th><th>СТАТУС</th><th>СУММА</th></tr></thead><tbody>${list.map(x=>`<tr data-id="${x.id}" onclick="openExpense('${x.id}')"><td><b>${esc(x.description)}</b></td><td>${esc(projectName(x.project_id))}</td><td>${esc(x.category)}</td><td>${date(x.expense_date)}</td><td><span class="status ${statusTone(x.payment_status)}">${esc(x.payment_status)}</span></td><td class="money">${money(x.actual_amount)} AED</td></tr>`).join('')||'<tr><td colspan="6"><div class="empty">Расходов пока нет</div></td></tr>'}</tbody></table></div>`}
  function movementTable(list){return `<div class="table-wrap"><table class="data-table"><thead><tr><th>ДАТА</th><th>ОПЕРАЦИЯ</th><th>МАТЕРИАЛ</th><th>ПРОЕКТ</th><th>КОЛ-ВО</th><th>СТОИМОСТЬ</th></tr></thead><tbody>${list.map(x=>`<tr><td>${date(x.movement_date)}</td><td><span class="status blue">${esc(movementName(x.movement_type))}</span></td><td>${esc(state.materials.find(m=>m.id===x.material_id)?.name||'—')}</td><td>${esc(projectName(x.project_id))}</td><td>${Number(x.quantity)||0}</td><td>${money(Number(x.quantity||0)*Number(x.unit_cost||0))} AED</td></tr>`).join('')||'<tr><td colspan="6"><div class="empty">Движений пока нет</div></td></tr>'}</tbody></table></div>`}

  clientsPage=function(){return `<div class="section-title"><div><h2>База клиентов</h2><p>Контакты, объекты и история проектов.</p></div></div><div class="cards">${state.clients.map(c=>`<article class="entity-card" onclick="openClient('${c.id}')"><h3>${esc(c.name)}</h3><p>${esc(c.company||c.client_type||'Частный клиент')}</p><div class="card-meta"><span class="tag">${esc(c.phone||'Нет телефона')}</span><span class="tag">${esc(c.area||'Dubai')}</span><span class="tag">${state.projects.filter(p=>p.client_id===c.id).length} проектов</span></div></article>`).join('')||'<div class="panel empty">Клиентов пока нет. Создайте первого клиента.</div>'}</div>`};
  taskTable=function(list){return `<div class="table-wrap"><table class="data-table"><thead><tr><th>ЗАДАЧА</th><th>ПРОЕКТ</th><th>ОТВЕТСТВЕННЫЙ</th><th>СТАТУС</th><th>ПРИОРИТЕТ</th><th>СРОК</th></tr></thead><tbody>${list.map(t=>`<tr data-id="${t.id}" onclick="openTask('${t.id}')"><td><b>${esc(t.title)}</b><br><small>${esc(t.description||'')}</small></td><td>${esc(projectName(t.project_id))}</td><td>${esc(employeeName(t.assignee_id))}</td><td><span class="status ${statusTone(t.status)}">${esc(taskStatus(t.status))}</span></td><td>${esc(t.priority)}</td><td>${date(t.due_date)}</td></tr>`).join('')||'<tr><td colspan="6"><div class="empty">Задач пока нет</div></td></tr>'}</tbody></table></div>`};
  expensesPage=function(){const total=state.expenses.reduce((a,x)=>a+Number(x.actual_amount||0),0);return `<div class="kpis">${kpi('AED','Фактические расходы',money(total),'AED')}${kpi('▣','Записей',state.expenses.length,'по всем проектам')}${kpi('◷','Не оплачено',state.expenses.filter(x=>x.payment_status!=='paid').length,'расходов')}${kpi('%','Средний расход',money(state.expenses.length?total/state.expenses.length:0),'AED')}</div><div class="panel">${expenseTable(state.expenses)}</div>`};
  materialsPage=function(){return `<div class="cards">${state.materials.map(m=>`<article class="entity-card" onclick="openMaterial('${m.id}')"><h3>${esc(m.name)}</h3><p>${esc([m.brand,m.color,m.dimensions].filter(Boolean).join(' · ')||'Материал')}</p><div class="card-meta"><span class="tag">${esc(m.unit)}</span><span class="tag">${money(m.purchase_price)} AED</span><span class="tag">Min: ${Number(m.minimum_stock)||0}</span></div></article>`).join('')||'<div class="panel empty">Материалов пока нет</div>'}</div>`};
  employeesPage=function(){return `<div class="cards">${state.employees.map(e=>`<article class="entity-card" onclick="openEmployee('${e.id}')"><h3>${esc(e.full_name)}</h3><p>${esc(e.job_title||'Сотрудник')} · ${esc(e.department||'Без отдела')}</p><div class="card-meta"><span class="tag">${esc(e.payment_type)}</span><span class="tag">${esc(e.status||'working')}</span><span class="tag">${esc(e.phone||'Нет телефона')}</span></div></article>`).join('')||'<div class="panel empty">Сотрудников пока нет</div>'}</div>`};
  warehousePage=function(){const stockMap=new Map();state.stock.forEach(x=>{const v=stockMap.get(x.material_id)||{on:0,res:0};v.on+=Number(x.quantity_on_hand||0);v.res+=Number(x.reserved||0);stockMap.set(x.material_id,v)});return `<div class="kpis">${kpi('▥','Материалов',state.materials.length,'в справочнике')}${kpi('↓','Приходов',state.movements.filter(x=>x.movement_type==='receipt').length,'операций')}${kpi('↔','Движений',state.movements.length,'последние 100')}${kpi('!','Низкий остаток',state.materials.filter(m=>{const s=stockMap.get(m.id)||{on:0,res:0};return s.on-s.res<=Number(m.minimum_stock||0)}).length,'позиций')}</div><div class="split-grid"><section class="panel"><div class="panel-head"><div><h2>Остатки</h2><p>С учётом резерва по всем складам</p></div></div>${simpleTable(['МАТЕРИАЛ','ЕДИНИЦА','НА СКЛАДЕ','РЕЗЕРВ','ДОСТУПНО','МИНИМУМ'],state.materials.map(m=>{const s=stockMap.get(m.id)||{on:0,res:0},available=s.on-s.res,low=available<=Number(m.minimum_stock||0);return [`<button class="btn" onclick="openMaterial('${m.id}')">${esc(m.name)}</button>`,esc(m.unit),s.on,s.res,`<span class="${low?'stock-low':''}">${available}</span>`,Number(m.minimum_stock)||0]}))}</section><section class="panel"><div class="panel-head"><div><h2>Последние операции</h2><p>Приход, выдача, резерв и списание</p></div></div>${movementTable(state.movements.slice(0,20))}</section></div>`};

  window.openWarehouseModal=(projectId='')=>openModal('Движение материала',select('movement_type','Операция',[['receipt','Приход'],['issue','Выдача на проект'],['reserve','Резерв'],['unreserve','Снять резерв'],['return','Возврат'],['transfer','Перемещение'],['writeoff','Списание'],['defect','Брак'],['inventory','Инвентаризация']].map(([v,n])=>`<option value="${v}">${n}</option>`).join(''))+select('material_id','Материал','<option value="">Выберите материал</option>'+optionList(state.materials,'id','name'))+select('warehouse_id','Основной склад','<option value="">Выберите склад</option>'+optionList(state.warehouses,'id','name'))+select('source_warehouse_id','Откуда (для перемещения)','<option value="">Не выбран</option>'+optionList(state.warehouses,'id','name'))+select('destination_warehouse_id','Куда (для перемещения)','<option value="">Не выбран</option>'+optionList(state.warehouses,'id','name'))+select('project_id','Проект','<option value="">Без проекта</option>'+optionList(state.projects,'id','name',projectId))+input('quantity','Количество','number','1','required step="0.001" min="0.001"')+input('unit_cost','Цена за единицу, AED','number','0','step="0.01"')+input('movement_date','Дата и время','datetime-local',isoNow())+input('reference','Документ / основание')+`<label class="full">Комментарий<textarea name="notes"></textarea></label>`,async d=>{if(!d.material_id)throw new Error('Выберите материал');if(d.movement_type==='transfer'&&(!d.source_warehouse_id||!d.destination_warehouse_id))throw new Error('Для перемещения выберите оба склада');return insert('stock_movements',{movement_type:d.movement_type,material_id:d.material_id,warehouse_id:d.movement_type==='transfer'?null:(d.warehouse_id||null),source_warehouse_id:d.movement_type==='transfer'?d.source_warehouse_id:null,destination_warehouse_id:d.movement_type==='transfer'?d.destination_warehouse_id:null,project_id:d.project_id||null,quantity:Number(d.quantity),unit_cost:Number(d.unit_cost||0),movement_date:d.movement_date?new Date(d.movement_date).toISOString():new Date().toISOString(),reference:d.reference||null,notes:d.notes||null,performed_by:state.profile?.id})});

  function dictionaryCard(g){const items=state.dictionaryItems.filter(x=>x.group_id===g.id);return `<article class="panel"><div class="panel-head"><div><h2>${esc(localized(g.name))}</h2><p>${esc(g.code)} · ${items.length} значений</p></div><button class="btn" onclick="openDictionaryModal('${g.id}')">＋</button></div><div class="side-list">${items.map(i=>`<div class="side-item clickable" onclick="openDictionaryModal('${g.id}','${i.id}')"><b>${esc(localized(i.name))}</b><p>${esc(i.code)} · ${i.is_active?'Активно':'Отключено'}</p></div>`).join('')||'<div class="empty">Нет значений</div>'}</div></article>`}
  settingsPage=function(){const b=brandSetting();return `<div class="panel"><div class="panel-head"><div><h2>Фирменный стиль</h2><p>Логотип и название в меню на всех устройствах</p></div><button class="btn primary" onclick="openBrandingModal()">Изменить</button></div><div class="brand-upload"><div class="brand-preview">${b.logo_url?`<img src="${esc(b.logo_url)}" alt="Логотип">`:'SB'}</div><div><b>${esc(b.brand_name||'SPACE BURO')}</b><p class="muted">Логотип хранится в защищённом облачном хранилище.</p></div></div></div><div class="section-title section-gap"><div><h2>Редактируемые справочники</h2><p>Новые категории и статусы можно добавлять без изменения кода.</p></div></div><div class="dictionary-grid">${state.dictionaryGroups.map(dictionaryCard).join('')}</div>`};
  window.openDictionaryModal=(groupId='',itemId='')=>{const item=state.dictionaryItems.find(x=>x.id===itemId)||{},groups=state.dictionaryGroups;openModal(itemId?'Изменить значение':'Новое значение',select('group_id','Справочник',optionList(groups,'id','code',groupId||item.group_id))+input('name_ru','Название на русском','text',localized(item.name)==='—'?'':localized(item.name),'required')+input('name_en','Название на английском','text',item.name?.en||'')+input('code','Системный код','text',item.code||'','required')+input('color','Цвет','color',item.color||'#2e73d2')+input('sort_order','Порядок','number',item.sort_order||0)+select('is_active','Статус',`<option value="true" ${item.is_active!==false?'selected':''}>Активно</option><option value="false" ${item.is_active===false?'selected':''}>Отключено</option>`),async d=>{const rec={group_id:d.group_id,name:{ru:d.name_ru,en:d.name_en||d.name_ru},code:d.code,color:d.color,sort_order:Number(d.sort_order||0),is_active:d.is_active==='true'};return itemId?update('dictionary_items',itemId,rec):insert('dictionary_items',rec)})};
  window.openBrandingModal=()=>{const b=brandSetting();openModal('Фирменный стиль',input('brand_name','Название компании','text',b.brand_name||'SPACE BURO')+'<label class="full">Логотип<input name="logo_file" type="file" accept="image/png,image/jpeg,image/webp,image/svg+xml"></label>'+input('logo_url','Или публичная ссылка на логотип','url',b.logo_url||'')+input('favicon_url','Публичная ссылка на favicon','url',b.favicon_url||''),async d=>{let logo_path=b.logo_path||null;if(d.logo_file instanceof File&&d.logo_file.size){const org=state.profile?.organization_id;if(!org)throw new Error('Не удалось определить компанию');logo_path=`${org}/branding/logo-${Date.now()}-${d.logo_file.name.replace(/[^a-zA-Z0-9._-]/g,'_')}`;await uploadObject(d.logo_file,logo_path)}await saveSetting('branding',{...b,brand_name:d.brand_name,logo_url:d.logo_url||null,logo_path,favicon_url:d.favicon_url||null})})};

  notificationsPage=function(){const unread=state.notifications.filter(n=>!n.read_at).length;return `<div class="kpis">${kpi('◉','Непрочитано',unread,'уведомлений')}${kpi('!','Просрочено',state.notifications.filter(n=>['task_overdue','project_late'].includes(n.notification_type)).length,'сроков')}${kpi('▥','Низкий остаток',state.notifications.filter(n=>n.notification_type==='low_stock').length,'материалов')}${kpi('✓','Всего',state.notifications.length,'последние записи')}</div><div class="cards">${state.notifications.map(n=>`<article class="entity-card notification-card ${n.read_at?'':'unread'}" onclick="markNotification('${n.id}')"><h3>${n.read_at?'':'● '}${esc(n.title)}</h3><p>${esc(n.message||'')}</p><div class="card-meta"><span class="tag">${date(n.due_at||n.created_at)}</span><span class="tag">${esc(n.notification_type)}</span></div></article>`).join('')||'<div class="panel empty">Уведомлений нет — всё под контролем.</div>'}</div>`};
  window.markNotification=async id=>{await update('notifications',id,{read_at:new Date().toISOString()});await loadAll();toast('Уведомление прочитано')};
  window.refreshNotifications=async()=>{await rawApi('/rest/v1/rpc/refresh_operational_notifications',{method:'POST',body:'{}'});await loadAll();toast('Уведомления обновлены')};

  function currentPayrollPeriod(){return state.payrollPeriods.find(p=>Number(p.period_year)===Number(state.payrollYear)&&Number(p.period_month)===Number(state.payrollMonth))}
  payrollPage=function(){const period=currentPayrollPeriod(),entries=period?state.payrollEntries.filter(e=>e.payroll_period_id===period.id):[],total=entries.reduce((a,x)=>a+Number(x.accrued||0),0),paid=entries.reduce((a,x)=>a+Number(x.paid||0),0);return `<div class="toolbar panel"><select class="field" onchange="setPayrollMonth(this.value)">${Array.from({length:12},(_,i)=>`<option value="${i+1}" ${state.payrollMonth===i+1?'selected':''}>${new Intl.DateTimeFormat('ru',{month:'long'}).format(new Date(2026,i,1))}</option>`).join('')}</select><select class="field" onchange="setPayrollYear(this.value)">${[state.payrollYear-1,state.payrollYear,state.payrollYear+1].map(y=>`<option ${state.payrollYear===y?'selected':''}>${y}</option>`).join('')}</select><button class="btn primary" onclick="calculatePayroll()">Рассчитать зарплату</button></div><div class="kpis">${kpi('AED','Начислено',money(total),'AED')}${kpi('↓','Выплачено',money(paid),'AED')}${kpi('◷','К выплате',money(total-paid),'AED')}${kpi('♟','Сотрудников',entries.length,period?`Статус: ${period.status}`:'Период не рассчитан')}</div><div class="panel">${simpleTable(['СОТРУДНИК','БАЗА','OVERTIME','БОНУСЫ','ШТРАФЫ','АВАНСЫ','НАЧИСЛЕНО','ОСТАТОК'],entries.map(e=>[esc(state.employees.find(x=>x.id===e.employee_id)?.full_name||'—'),money(Number(e.base_amount)+Number(e.daily_amount)+Number(e.hourly_amount)),money(e.overtime_amount),money(e.bonuses),money(e.penalties),money(e.advances),money(e.accrued)+' AED',`<b>${money(e.balance)} AED</b>`]))}</div><div class="panel section-gap"><div class="panel-head"><div><h2>Корректировки</h2><p>Авансы, бонусы, штрафы и оплата за проект</p></div></div>${simpleTable(['ДАТА','СОТРУДНИК','ТИП','ПРОЕКТ','СУММА'],state.payrollAdjustments.slice(0,30).map(a=>[date(a.adjustment_date),esc(state.employees.find(e=>e.id===a.employee_id)?.full_name||'—'),esc(a.adjustment_type),esc(projectName(a.project_id)),money(a.amount)+' AED']))}</div>`};
  window.setPayrollMonth=v=>{state.payrollMonth=Number(v);renderPage()};window.setPayrollYear=v=>{state.payrollYear=Number(v);renderPage()};
  window.calculatePayroll=async()=>{await rawApi('/rest/v1/rpc/calculate_payroll',{method:'POST',body:JSON.stringify({p_year:state.payrollYear,p_month:state.payrollMonth})});await loadAll();toast('Зарплата рассчитана')};
  window.openPayrollAdjustment=()=>openModal('Корректировка зарплаты',select('employee_id','Сотрудник','<option value="">Выберите сотрудника</option>'+optionList(state.employees,'id','full_name'))+select('project_id','Проект','<option value="">Без проекта</option>'+optionList(state.projects,'id','name'))+select('adjustment_type','Тип','<option value="advance">Аванс</option><option value="bonus">Бонус</option><option value="penalty">Штраф</option><option value="project_payment">Оплата за проект</option><option value="other">Другое</option>')+input('amount','Сумма, AED','number','0','required step="0.01"')+input('adjustment_date','Дата','date',new Date().toISOString().slice(0,10))+`<label class="full">Комментарий<textarea name="notes"></textarea></label>`,async d=>{if(!d.employee_id)throw new Error('Выберите сотрудника');return insert('payroll_adjustments',{...d,project_id:d.project_id||null,amount:Number(d.amount||0)})});

  renderPage=function(){const map={dashboard,projects:projectsPage,clients:clientsPage,tasks:tasksPage,gantt:ganttPage,expenses:expensesPage,payments:paymentsPage,materials:materialsPage,warehouse:warehousePage,employees:employeesPage,settings:settingsPage,notifications:notificationsPage,payroll:payrollPage};$('#content').innerHTML=(map[state.page]||dashboard)();bindPageFilters()};
  actionForPage=function(){if(state.page==='clients')return openClientModal();if(state.page==='tasks'||state.page==='gantt')return openTaskModal();if(state.page==='expenses')return openExpenseModal();if(state.page==='payments')return openPaymentModal();if(state.page==='materials')return openMaterialModal();if(state.page==='employees')return openEmployeeModal();if(state.page==='warehouse')return openWarehouseModal();if(state.page==='settings')return openDictionaryModal();if(state.page==='notifications')return refreshNotifications();if(state.page==='payroll')return openPayrollAdjustment();openProjectModal()};
  $('#pageAction').onclick=actionForPage;
  $('#modalForm').onsubmit=async e=>{e.preventDefault();$('#modalSubmit').disabled=true;const d=Object.fromEntries(new FormData(e.target));try{await modalHandler(d);$('#modalOverlay').classList.remove('show');$('#drawerOverlay').classList.remove('show');e.target.reset();await loadAll();toast('Данные сохранены в облаке')}catch(err){toast(err.message)}finally{$('#modalSubmit').disabled=false}};
  $$('.nav-btn').forEach(b=>b.onclick=()=>setPage(b.dataset.page));
  if(state.session?.access_token)loadAll().catch(e=>toast(e.message));else renderPage();
})();
