(function(){
  const SVG={
    dashboard:'<rect x="3" y="3" width="7" height="7" rx="1"/><rect x="14" y="3" width="7" height="7" rx="1"/><rect x="3" y="14" width="7" height="7" rx="1"/><rect x="14" y="14" width="7" height="7" rx="1"/>',
    users:'<path d="M16 21v-2a4 4 0 0 0-4-4H6a4 4 0 0 0-4 4v2"/><circle cx="9" cy="7" r="4"/><path d="M22 21v-2a4 4 0 0 0-3-3.87M16 3.13a4 4 0 0 1 0 7.75"/>',
    folder:'<path d="M3 6a2 2 0 0 1 2-2h5l2 2h7a2 2 0 0 1 2 2v9a3 3 0 0 1-3 3H5a2 2 0 0 1-2-2z"/>',
    'check-square':'<polyline points="9 11 12 14 22 4"/><path d="M21 12v7a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2V5a2 2 0 0 1 2-2h11"/>',
    gantt:'<path d="M3 5h18M3 12h18M3 19h18"/><path d="M6 3v4M14 10v4M9 17v4M18 17v4"/>',
    layers:'<polygon points="12 2 2 7 12 12 22 7 12 2"/><polyline points="2 17 12 22 22 17"/><polyline points="2 12 12 17 22 12"/>',
    truck:'<path d="M3 6h11v11H3zM14 10h4l3 3v4h-7z"/><circle cx="7" cy="19" r="2"/><circle cx="18" cy="19" r="2"/>',
    warehouse:'<path d="M3 21V8l9-5 9 5v13"/><path d="M7 21v-8h10v8M7 16h10"/>',
    'book-open':'<path d="M2 4h6a4 4 0 0 1 4 4v13a4 4 0 0 0-4-4H2zM22 4h-6a4 4 0 0 0-4 4v13a4 4 0 0 1 4-4h6z"/>',
    'id-card':'<rect x="3" y="5" width="18" height="14" rx="2"/><circle cx="8" cy="11" r="2"/><path d="M5.5 16c.8-2 4.2-2 5 0M13 10h5M13 14h4"/>',
    receipt:'<path d="M5 3h14v18l-3-2-2 2-2-2-2 2-2-2-3 2z"/><path d="M9 8h6M9 12h6M9 16h3"/>',
    wallet:'<path d="M3 6h16a2 2 0 0 1 2 2v10a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2z"/><path d="M16 11h5v5h-5a2.5 2.5 0 0 1 0-5zM3 8V5a2 2 0 0 1 2-2h12"/>',
    banknote:'<rect x="2" y="5" width="20" height="14" rx="2"/><circle cx="12" cy="12" r="3"/><path d="M6 9H5v1M18 15h1v-1"/>',
    chart:'<path d="M4 20V10M10 20V4M16 20v-7M22 20H2"/>',
    bell:'<path d="M18 8a6 6 0 0 0-12 0c0 7-3 7-3 9h18c0-2-3-2-3-9M10 21h4"/>',
    settings:'<circle cx="12" cy="12" r="3"/><path d="M19.4 15a1.7 1.7 0 0 0 .3 1.9l.1.1-2.8 2.8-.1-.1a1.7 1.7 0 0 0-1.9-.3 1.7 1.7 0 0 0-1 1.6v.2h-4V21a1.7 1.7 0 0 0-1-1.6 1.7 1.7 0 0 0-1.9.3l-.1.1L4.2 17l.1-.1a1.7 1.7 0 0 0 .3-1.9A1.7 1.7 0 0 0 3 14H2.8v-4H3a1.7 1.7 0 0 0 1.6-1 1.7 1.7 0 0 0-.3-1.9L4.2 7 7 4.2l.1.1A1.7 1.7 0 0 0 9 4.6a1.7 1.7 0 0 0 1-1.6v-.2h4V3a1.7 1.7 0 0 0 1 1.6 1.7 1.7 0 0 0 1.9-.3l.1-.1L19.8 7l-.1.1a1.7 1.7 0 0 0-.3 1.9 1.7 1.7 0 0 0 1.6 1h.2v4H21a1.7 1.7 0 0 0-1.6 1z"/>',
    'panel-left':'<rect x="3" y="3" width="18" height="18" rx="2"/><path d="M9 3v18M14 9l-3 3 3 3"/>',
    calculator:'<rect x="4" y="2" width="16" height="20" rx="2"/><path d="M8 6h8M8 11h.01M12 11h.01M16 11h.01M8 15h.01M12 15h.01M16 15h.01M8 19h.01M12 19h4"/>',
    calendar:'<rect x="3" y="4" width="18" height="17" rx="2"/><path d="M8 2v4M16 2v4M3 9h18M8 13h3M13 13h3M8 17h3"/>',
    landmark:'<path d="m3 10 9-7 9 7M5 10h14M6 10v8M10 10v8M14 10v8M18 10v8M3 21h18"/>',
    'shopping-cart':'<circle cx="9" cy="20" r="1"/><circle cx="19" cy="20" r="1"/><path d="M3 4h2l3 11h11l2-7H7"/>',
    'hard-hat':'<path d="M2 18h20M5 18v-3a7 7 0 0 1 14 0v3M9 15V7M15 15V7"/>',
    alert:'<circle cx="12" cy="12" r="9"/><path d="M12 7v6M12 17h.01"/>',
    money:'<circle cx="12" cy="12" r="9"/><path d="M16 8.5c-.8-.7-2-1-3.4-1-1.8 0-3.1.8-3.1 2s1.1 1.8 3.2 2.3 3.1 1 3.1 2.4-1.3 2.3-3.3 2.3c-1.5 0-2.8-.4-3.7-1.2M12 5v14"/>',
    clock:'<circle cx="12" cy="12" r="9"/><path d="M12 7v5l3 2"/>',
    package:'<path d="m3 7 9-5 9 5v10l-9 5-9-5zM3 7l9 5 9-5M12 12v10"/>',
    activity:'<path d="M3 12h4l2-7 4 14 2-7h6"/>'
  };
  const icon=name=>`<svg class="sb-icon" viewBox="0 0 24 24" aria-hidden="true">${SVG[name]||SVG.package}</svg>`;
  function paintIcons(){document.querySelectorAll('[data-icon]').forEach(el=>{el.innerHTML=icon(el.dataset.icon)});document.querySelectorAll('.kpi-icon:not(:has(svg))').forEach(el=>{const label=el.parentElement?.querySelector('.kpi-label')?.textContent?.toLowerCase()||'',name=label.includes('зарп')?'banknote':label.includes('расход')?'receipt':label.includes('плат')||label.includes('получ')?'wallet':label.includes('проект')?'folder':label.includes('задач')?'check-square':label.includes('склад')||label.includes('материал')?'package':label.includes('срок')||label.includes('задерж')?'clock':'activity';el.innerHTML=icon(name)})}
  const local=v=>typeof v==='object'&&v?(v.ru||v.en||Object.values(v)[0]||'—'):(v||'—');
  const safe=path=>rawApi(path).catch(()=>[]);
  const groupItems=code=>{const g=state.dictionaryGroups.find(x=>x.code===code);return g?state.dictionaryItems.filter(x=>x.group_id===g.id&&x.is_active!==false):[]};
  const opts=(rows,value='id',label='name',selected='')=>rows.map(x=>`<option value="${esc(x[value])}" ${String(x[value])===String(selected)?'selected':''}>${esc(local(x[label]))}</option>`).join('');
  const unitOptions=selected=>opts(groupItems('unit'),'code','name',selected);
  const projectLabel=id=>state.projects.find(x=>x.id===id)?.name||'Без проекта';
  const employeeLabel=id=>state.employees.find(x=>x.id===id)?.full_name||'—';
  const baseLoadAll=loadAll,baseRenderPage=renderPage,baseUpdateShell=updateShell,baseAction=actionForPage,baseSettings=settingsPage,baseInput=input,baseEditRecord=window.editRecord,baseOpenEmployee=window.openEmployee;
  Object.assign(state,{materialSubcategories:[],supplierMaterials:[],payrollSettings:[],attendanceEvents:[],designRules:[],designCompensations:[],designPrograms:[],designStages:[],taskDependencies:[],taskComments:[],employeePhotos:{},payrollTab:'summary',procurementTab:'orders',ganttMonth:new Date(new Date().getFullYear(),new Date().getMonth(),1),ganttProject:''});
  Object.assign(pageMeta,{suppliers:['Поставщики','Новый поставщик']});

  input=function(name,label,type='text',value='',extra=''){
    if(name==='unit'&&type==='text')return select(name,label,unitOptions(value));
    if(['area','district','location'].includes(name)&&type==='text'){
      const rows=groupItems('dubai_area'),custom=value&&!rows.some(x=>x.code===value||local(x.name)===value)?`<option selected>${esc(value)}</option>`:'';
      return select(name,label,custom+`<option value="">Не выбран</option>`+rows.map(x=>`<option value="${esc(local(x.name))}" ${local(x.name)===value?'selected':''}>${esc(local(x.name))}</option>`).join(''));
    }
    return baseInput(name,label,type,value,extra);
  };

  loadAll=async function(){
    await baseLoadAll();
    const payroll=['owner','admin','accountant'].includes(state.profile?.role),design=['owner','admin','accountant','project_manager','designer'].includes(state.profile?.role);
    const all=await Promise.all([
      safe('/rest/v1/material_subcategories?select=*&is_active=eq.true&order=sort_order.asc'),
      safe('/rest/v1/supplier_materials?select=*&order=updated_at.desc'),
      payroll?safe('/rest/v1/payroll_settings?select=*'):[],
      payroll?safe('/rest/v1/payroll_attendance_events?select=*&order=event_date.desc&limit=1000'):[],
      design?safe('/rest/v1/design_payment_rules?select=*&is_active=eq.true&order=sort_order.asc'):[],
      design?safe('/rest/v1/design_compensations?select=*&order=updated_at.desc'):[],
      design?safe('/rest/v1/design_program_entries?select=*&order=created_at.asc'):[],
      design?safe('/rest/v1/design_stage_entries?select=*&order=sort_order.asc'):[],
      safe('/rest/v1/task_dependencies?select=*&order=created_at.asc'),
      safe('/rest/v1/task_comments?select=*&order=created_at.desc&limit=1000')
    ]);
    [state.materialSubcategories,state.supplierMaterials,state.payrollSettings,state.attendanceEvents,state.designRules,state.designCompensations,state.designPrograms,state.designStages,state.taskDependencies,state.taskComments]=all;
    await loadEmployeePhotos();updateShell();renderPage();
  };
  async function loadEmployeePhotos(){
    const rows=state.employees.filter(e=>e.photo_url&&!/^https?:|^data:/.test(e.photo_url));
    await Promise.all(rows.map(async e=>{try{const d=await rawApi('/storage/v1/object/sign/company-files/'+e.photo_url.split('/').map(encodeURIComponent).join('/'),{method:'POST',body:JSON.stringify({expiresIn:3600})});state.employeePhotos[e.id]=d?.signedURL?SUPABASE_URL+d.signedURL:null}catch{}}));
  }

  updateShell=function(){baseUpdateShell();const role=state.profile?.role;const visibility={suppliers:['owner','admin','procurement','project_manager'],rate_catalog:['owner','admin','project_manager','procurement'],management_reports:['owner','admin','accountant']} ;Object.entries(visibility).forEach(([page,roles])=>{const b=document.querySelector(`.nav-btn[data-page="${page}"]`);if(b)b.classList.toggle('hidden',!roles.includes(role))});paintIcons();document.querySelectorAll('.nav-btn').forEach(b=>b.title=b.querySelector('.nav-text')?.textContent||'');};
  const collapsed=localStorage.getItem('sb-sidebar-collapsed')==='true';$('#sidebar').classList.toggle('collapsed',collapsed);
  $('#sidebarToggle').onclick=()=>{const next=!$('#sidebar').classList.contains('collapsed');$('#sidebar').classList.toggle('collapsed',next);localStorage.setItem('sb-sidebar-collapsed',String(next));$('#sidebarToggle').title=next?'Развернуть меню':'Свернуть меню'};

  const metric=(name,label,value,note)=>`<article class="kpi"><div class="kpi-icon">${icon(name)}</div><div><div class="kpi-label">${esc(label)}</div><div class="kpi-value">${value}</div><small>${esc(note||'')}</small></div></article>`;
  dashboard=function(){
    const active=state.projects.filter(p=>p.status!=='Завершён'&&p.status!=='completed'),late=active.filter(p=>p.due_date&&new Date(p.due_date)<new Date()),open=state.tasks.filter(t=>t.status!=='completed'),overdue=open.filter(t=>t.due_date&&new Date(t.due_date)<new Date());
    const income=state.payments.filter(p=>p.direction==='income'&&p.status==='paid').reduce((a,x)=>a+Number(x.amount||0),0),expected=state.payments.filter(p=>p.direction==='income'&&p.status!=='paid').reduce((a,x)=>a+Number(x.amount||0),0),expenses=state.expenses.reduce((a,x)=>a+Number(x.actual_amount||0),0);
    const period=state.payrollPeriods.find(p=>Number(p.period_year)===state.payrollYear&&Number(p.period_month)===state.payrollMonth),salary=period?state.payrollEntries.filter(e=>e.payroll_period_id===period.id).reduce((a,x)=>a+Number(x.accrued||0),0):0;
    const contract=active.reduce((a,x)=>a+Number(x.contract_amount||x.budget||0),0),profit=income-expenses-salary,stockValue=state.stock.reduce((a,x)=>a+Number(x.inventory_value||0),0);
    const types={};state.projects.forEach(p=>types[p.category||'Без категории']=(types[p.category||'Без категории']||0)+1);const statuses={};state.projects.forEach(p=>statuses[p.status||'Без статуса']=(statuses[p.status||'Без статуса']||0)+1);
    const colors=['#2e73d2','#7656c4','#1b9362','#c78817','#c95750','#48a7a0'],total=Math.max(1,state.projects.length);let cursor=0,stops=Object.values(statuses).map((v,i)=>{const a=cursor,b=cursor+=v/total*100;return `${colors[i%colors.length]} ${a}% ${b}%`}).join(',')||'#e7edf4 0 100%';
    const categories={};state.expenses.forEach(x=>categories[x.category||'Другое']=(categories[x.category||'Другое']||0)+Number(x.actual_amount||0));const maxExpense=Math.max(1,...Object.values(categories));
    return `<div class="kpis">${metric('folder','Активные проекты',active.length,late.length+' с задержкой')}${metric('money','Сумма активных проектов',money(contract)+' AED','Договорный объём')}${metric('wallet','Получено',money(income)+' AED',money(expected)+' AED ожидается')}${metric('receipt','Расходы',money(expenses)+' AED','без зарплат')}${metric('banknote','Зарплата за месяц',money(salary)+' AED','начислено')}${metric('chart','Операционная разница',money(profit)+' AED','платежи − расходы − зарплата')}${metric('check-square','Открытые задачи',open.length,overdue.length+' просрочено')}${metric('package','Стоимость склада',money(stockValue)+' AED',state.materials.length+' материалов')}</div>
    <div class="dashboard-charts"><section class="panel"><div class="panel-head"><div><h2>Проекты по статусам</h2><p>Распределение текущего портфеля</p></div></div><div class="donut-wrap"><div class="donut" style="background:conic-gradient(${stops})"></div><div class="legend">${Object.entries(statuses).map(([n,v],i)=>`<div><i style="background:${colors[i%colors.length]}"></i><span>${esc(n)}</span><b>${v}</b></div>`).join('')||'<span class="muted">Нет данных</span>'}</div></div></section>
    <section class="panel"><div class="panel-head"><div><h2>Расходы по категориям</h2><p>Фактические операции</p></div></div><div class="chart-card">${Object.entries(categories).sort((a,b)=>b[1]-a[1]).slice(0,7).map(([n,v])=>`<div class="chart-row"><span>${esc(n)}</span><div class="chart-track"><i style="width:${v/maxExpense*100}%;background:var(--blue)"></i></div><b>${money(v)}</b></div>`).join('')||'<div class="empty">Расходов пока нет</div>'}</div></section>
    <section class="panel"><div class="panel-head"><div><h2>Проекты по типам</h2><p>Загрузка компании</p></div></div><div class="chart-card">${Object.entries(types).map(([n,v],i)=>`<div class="chart-row"><span>${esc(n)}</span><div class="chart-track"><i style="width:${v/Math.max(1,...Object.values(types))*100}%;background:${colors[i%colors.length]}"></i></div><b>${v}</b></div>`).join('')||'<div class="empty">Проектов пока нет</div>'}</div></section></div>
    <div class="dashboard-grid section-gap"><section class="panel"><div class="panel-head"><div><h2>Проекты: сроки, бюджет и прогресс</h2><p>Главная оперативная картина</p></div><button class="btn" onclick="setPage('projects')">Все проекты →</button></div>${projectTable(active.slice(0,10))}</section><section class="panel"><div class="panel-head"><div><h2>Финансовый пульс</h2><p>Сводка по компании</p></div></div><div class="finance-summary"><div class="summary-line"><span>Договорный объём</span><b>${money(contract)} AED</b></div><div class="summary-line"><span>Получено</span><b>${money(income)} AED</b></div><div class="summary-line"><span>Ожидается</span><b>${money(expected)} AED</b></div><div class="summary-line"><span>Расходы</span><b>${money(expenses)} AED</b></div><div class="summary-line"><span>Зарплаты</span><b>${money(salary)} AED</b></div><div class="summary-line"><span>Операционная разница</span><b class="${profit<0?'stock-low':''}">${money(profit)} AED</b></div></div></section></div>`;
  };

  function daysInMonth(d){return new Date(d.getFullYear(),d.getMonth()+1,0).getDate()}
  ganttPage=function(){
    const month=state.ganttMonth,days=daysInMonth(month),start=new Date(month.getFullYear(),month.getMonth(),1),end=new Date(month.getFullYear(),month.getMonth(),days,23,59,59),today=new Date();
    const items=state.tasks.filter(t=>t.start_date&&t.due_date&&(!state.ganttProject||t.project_id===state.ganttProject)&&new Date(t.due_date)>=start&&new Date(t.start_date)<=end);
    const dayHeaders=Array.from({length:days},(_,i)=>{const d=new Date(month.getFullYear(),month.getMonth(),i+1),weekend=[0,6].includes(d.getDay()),isToday=d.toDateString()===today.toDateString();return `<div class="gantt-day ${weekend?'weekend':''} ${isToday?'today':''}">${i+1}<br>${new Intl.DateTimeFormat('ru',{weekday:'short'}).format(d).slice(0,2)}</div>`}).join('');
    return `<div class="toolbar panel"><button class="btn" onclick="changeGanttMonth(-1)">←</button><button class="btn" onclick="ganttToday()">Сегодня</button><button class="btn" onclick="changeGanttMonth(1)">→</button><b style="align-self:center">${new Intl.DateTimeFormat('ru',{month:'long',year:'numeric'}).format(month)}</b><select class="field" onchange="setGanttProject(this.value)"><option value="">Все проекты</option>${opts(state.projects,'id','name',state.ganttProject)}</select><button class="btn primary" onclick="openTaskDependency()">Связать работы</button></div><div class="panel section-gap"><div class="panel-head"><div><h2>Расширенная диаграмма Ганта</h2><p>Месяц на одном экране · связи FS / SS / FF / SF · комментарии</p></div><span class="tag">${items.length} работ</span></div><div class="gantt-wrap"><div class="gantt-month"><div class="gantt-head"><div class="gantt-name"><b>Задача / проект</b><small>Комментарий и связи</small></div><div class="gantt-month-grid" style="grid-template-columns:repeat(${days},1fr)">${dayHeaders}</div></div>${items.map(t=>{const s=Math.max(1,new Date(t.start_date).getDate()),e=Math.min(days,new Date(t.due_date).getDate()),left=(s-1)/days*100,width=Math.max(100/days,(e-s+1)/days*100),late=t.status!=='completed'&&new Date(t.due_date)<today,comments=state.taskComments.filter(x=>x.task_id===t.id),links=state.taskDependencies.filter(x=>x.predecessor_task_id===t.id||x.successor_task_id===t.id);return `<div class="gantt-row"><div class="gantt-name"><b>${esc(t.title)}</b><small>${esc(projectLabel(t.project_id))} · ${Number(t.progress)||0}%</small><div class="gantt-actions"><button onclick="openTaskComment('${t.id}')">Комментарий · ${comments.length}</button><button onclick="openTaskDependency('${t.id}')">Связи · ${links.length}</button></div></div><div class="gantt-lane" style="grid-template-columns:repeat(${days},1fr)">${Array.from({length:days},(_,i)=>{const d=new Date(month.getFullYear(),month.getMonth(),i+1);return `<i class="gantt-cell ${[0,6].includes(d.getDay())?'weekend':''} ${d.toDateString()===today.toDateString()?'today':''}"></i>`}).join('')}<div class="gantt-task-bar ${late?'late':''}" style="left:${left}%;width:${width}%" title="${esc(comments[0]?.comment||'Без комментария')}">${esc(t.title)} · ${Number(t.progress)||0}%</div></div></div>`}).join('')||'<div class="empty">В этом месяце нет задач с датами начала и завершения.</div>'}</div></div></div>`;
  };
  window.changeGanttMonth=n=>{state.ganttMonth=new Date(state.ganttMonth.getFullYear(),state.ganttMonth.getMonth()+n,1);renderPage()};
  window.ganttToday=()=>{state.ganttMonth=new Date(new Date().getFullYear(),new Date().getMonth(),1);renderPage()};
  window.setGanttProject=v=>{state.ganttProject=v;renderPage()};
  window.openTaskComment=taskId=>openModal('Комментарий к работе',select('task_id','Работа',opts(state.tasks,'id','title',taskId))+`<label class="full">Комментарий<textarea name="comment" required></textarea></label>`,async d=>insert('task_comments',{task_id:d.task_id,comment:d.comment}));
  window.openTaskDependency=taskId=>openModal('Связать две работы',select('predecessor_task_id','Предыдущая работа',`<option value="">Выберите</option>`+opts(state.tasks,'id','title',taskId))+select('successor_task_id','Следующая работа',`<option value="">Выберите</option>`+opts(state.tasks,'id','title'))+select('dependency_type','Тип связи','<option value="finish_to_start">Finish → Start</option><option value="start_to_start">Start → Start</option><option value="finish_to_finish">Finish → Finish</option><option value="start_to_finish">Start → Finish</option>')+input('lag_days','Сдвиг, дней','number','0')+`<label class="full">Комментарий к связи<textarea name="comment"></textarea></label>`,async d=>{if(!d.predecessor_task_id||!d.successor_task_id)throw new Error('Выберите обе работы');if(d.predecessor_task_id===d.successor_task_id)throw new Error('Нельзя связать работу саму с собой');return insert('task_dependencies',{predecessor_task_id:d.predecessor_task_id,successor_task_id:d.successor_task_id,dependency_type:d.dependency_type,lag_days:Number(d.lag_days||0),comment:d.comment||null})});

  function materialCategoryName(id){const c=state.materialCategories.find(x=>x.id===id);return c?local(c.name):'Без категории'}
  materialsPage=function(){return `<div class="toolbar panel"><input class="field search" placeholder="Поиск материала, бренда или категории" oninput="filterCards(this.value)"><button class="btn" onclick="setPage('settings')">Библиотеки</button></div><div class="cards section-gap" id="cardGrid">${state.materials.map(m=>{const cat=materialCategoryName(m.category_id),sub=local(state.materialSubcategories.find(x=>x.id===m.subcategory_id)?.name)||m.subcategory||'Без подкатегории',brand=state.brands.find(x=>x.id===m.brand_id)?.name||m.brand||'Без бренда';return `<article class="entity-card" data-search="${esc([m.name,cat,sub,brand].join(' ').toLowerCase())}" onclick="openMaterial('${m.id}')">${m.photo_url&&/^https?:|^data:/.test(m.photo_url)?`<img src="${esc(m.photo_url)}" alt="" style="width:100%;height:120px;object-fit:cover;border-radius:9px;margin-bottom:12px">`:''}<h3>${esc(m.name)}</h3><p>${esc(cat)} → ${esc(sub)}<br>${esc(brand)}</p><div class="card-meta"><span class="tag">${esc(m.unit)}</span><span class="tag">${money(m.purchase_price)} AED</span><span class="tag">Мин.: ${Number(m.minimum_stock||0)}</span></div></article>`}).join('')||'<div class="panel empty">Материалов пока нет</div>'}</div>`};
  window.filterCards=q=>document.querySelectorAll('#cardGrid [data-search]').forEach(x=>x.classList.toggle('hidden',!x.dataset.search.includes(q.toLowerCase())));
  function materialForm(m={}){const cat=m.category_id||'',subs=state.materialSubcategories.filter(x=>!cat||x.category_id===cat),templates=state.materialTemplates;return `<label class="full">Готовый материал<select name="template_id" onchange="fillMaterialTemplate(this.value)"><option value="">Выберите из готового списка или введите свой</option>${templates.map(t=>`<option value="${t.id}">${esc(t.name)} · ${esc(t.subcategory||t.category)}</option>`).join('')}</select></label>`+input('name','Название','text',m.name||'','required list="materialNameList"')+`<datalist id="materialNameList">${templates.map(t=>`<option value="${esc(t.name)}"></option>`).join('')}</datalist>`+input('code','Код / артикул','text',m.code||'')+select('category_id','Категория',`<option value="">Выберите категорию</option>`+opts(state.materialCategories,'id','name',cat))+select('subcategory_id','Подкатегория',`<option value="">Выберите подкатегорию</option>`+opts(subs,'id','name',m.subcategory_id||''))+select('brand_id','Бренд из библиотеки',`<option value="">Без бренда</option>`+opts(state.brands,'id','name',m.brand_id||''))+select('supplier_id','Основной поставщик',`<option value="">Без поставщика</option>`+opts(state.suppliers,'id','name',m.supplier_id||''))+input('color','Цвет / декор','text',m.color||'')+input('dimensions','Размер','text',m.dimensions||'')+input('thickness','Толщина, мм','number',m.thickness||'')+select('unit','Единица измерения',unitOptions(m.unit||'pcs'))+input('purchase_price','Закупочная цена, AED','number',m.purchase_price||0,'step="0.01"')+input('sale_price','Цена продажи, AED','number',m.sale_price||0,'step="0.01"')+input('minimum_stock','Минимальный остаток','number',m.minimum_stock||0,'step="0.001"')+input('minimum_order_quantity','Минимальный заказ','number',m.minimum_order_quantity||0,'step="0.001"')+`<label class="full">Комментарий<textarea name="notes">${esc(m.notes||'')}</textarea></label>`}
  const materialRecord=d=>{const sub=state.materialSubcategories.find(x=>x.id===d.subcategory_id);return {name:d.name,code:d.code||null,category_id:d.category_id||null,subcategory_id:d.subcategory_id||null,subcategory:sub?local(sub.name):null,brand_id:d.brand_id||null,supplier_id:d.supplier_id||null,color:d.color||null,dimensions:d.dimensions||null,thickness:d.thickness?Number(d.thickness):null,unit:d.unit||'pcs',purchase_price:Number(d.purchase_price||0),sale_price:Number(d.sale_price||0),minimum_stock:Number(d.minimum_stock||0),minimum_order_quantity:Number(d.minimum_order_quantity||0),notes:d.notes||null}};
  openMaterialModal=function(){openModal('Новый материал',materialForm(),async d=>insert('materials',materialRecord(d)));setTimeout(bindMaterialCategory,0)};
  function openMaterialEdit14(id){const m=state.materials.find(x=>x.id===id);openModal('Изменить материал',materialForm(m),async d=>update('materials',id,materialRecord(d)));setTimeout(bindMaterialCategory,0)}
  window.fillMaterialTemplate=id=>{const t=state.materialTemplates.find(x=>x.id===id),f=$('#modalForm');if(!t||!f)return;f.elements.name.value=t.name||'';f.elements.unit.value=t.unit||'pcs';const cat=state.materialCategories.find(x=>x.code===t.category);if(cat){f.elements.category_id.value=cat.id;bindMaterialCategory();const sub=state.materialSubcategories.find(x=>x.category_id===cat.id&&local(x.name).toLowerCase().includes(String(t.subcategory||'').toLowerCase()));if(sub)f.elements.subcategory_id.value=sub.id}};
  function bindMaterialCategory(){const f=$('#modalForm'),cat=f?.elements.category_id,sub=f?.elements.subcategory_id;if(!cat||!sub)return;const refresh=()=>{const current=sub.value;sub.innerHTML='<option value="">Выберите подкатегорию</option>'+opts(state.materialSubcategories.filter(x=>x.category_id===cat.value),'id','name',current)};cat.onchange=refresh;refresh()}

  function suppliersPage(){const preferred=state.supplierMaterials.filter(x=>x.is_preferred).length;return `<div class="kpis">${metric('truck','Поставщиков',state.suppliers.length,'активная библиотека')}${metric('layers','Материалов поставщиков',state.supplierMaterials.length,'цены и артикулы')}${metric('check-square','Предпочтительных связей',preferred,'основные поставщики')}${metric('clock','Средний срок',Math.round(state.suppliers.reduce((a,x)=>a+Number(x.lead_time_days||0),0)/Math.max(1,state.suppliers.length))+' дн.','доставка')}</div><div class="toolbar panel"><button class="btn primary" onclick="openSupplierModal()">＋ Поставщик</button><button class="btn" onclick="openSupplierMaterialModal()">＋ Материал поставщика</button><button class="btn" onclick="setPage('procurement')">Перейти в снабжение →</button></div><div class="cards section-gap">${state.suppliers.map(s=>`<article class="entity-card" onclick="openSupplierModal('${s.id}')"><div class="employee-card-head"><div class="employee-photo">${esc(s.name.slice(0,2).toUpperCase())}</div><div><h3>${esc(s.name)}</h3><p>${esc(s.contact_person||'Контакт не указан')}</p></div></div><div class="card-meta section-gap"><span class="tag">${esc(s.category||s.supplier_type||'Материалы')}</span><span class="tag">${esc(s.phone||s.whatsapp||'Нет телефона')}</span><span class="tag">${Number(s.lead_time_days||0)} дн.</span></div></article>`).join('')||'<div class="panel empty">Поставщиков пока нет</div>'}</div>`}
  window.openSupplierModal=id=>{const s=state.suppliers.find(x=>x.id===id)||{};openModal(id?'Изменить поставщика':'Новый поставщик',input('name','Название','text',s.name||'','required')+input('contact_person','Контактное лицо','text',s.contact_person||'')+input('phone','Телефон','text',s.phone||'')+input('whatsapp','WhatsApp','text',s.whatsapp||'')+input('email','Email','email',s.email||'')+input('address','Адрес','text',s.address||'')+select('supplier_type','Тип','<option value="material_supplier">Поставщик материалов</option><option value="contractor">Подрядчик</option><option value="service">Услуги</option><option value="mixed">Смешанный</option>')+input('category','Категории поставки','text',s.category||'')+input('lead_time_days','Срок поставки, дней','number',s.lead_time_days||0)+input('payment_terms','Условия оплаты','text',s.payment_terms||'')+input('delivery_terms','Условия доставки','text',s.delivery_terms||'')+`<label class="full">Комментарий<textarea name="notes">${esc(s.notes||'')}</textarea></label>`,async d=>{const rec={...d,lead_time_days:Number(d.lead_time_days||0)};return id?update('suppliers',id,rec):insert('suppliers',rec)})};
  window.openSupplierMaterialModal=()=>openModal('Материал поставщика',select('supplier_id','Поставщик','<option value="">Выберите</option>'+opts(state.suppliers))+select('material_id','Материал','<option value="">Выберите</option>'+opts(state.materials))+input('supplier_sku','Артикул поставщика')+select('unit','Единица',unitOptions('pcs'))+input('unit_price','Цена','number','0','step="0.01"')+input('minimum_order_quantity','Минимальный заказ','number','0','step="0.001"')+input('lead_time_days','Срок, дней','number','0')+select('is_preferred','Основной поставщик','<option value="false">Нет</option><option value="true">Да</option>')+`<label class="full">Комментарий<textarea name="notes"></textarea></label>`,async d=>{if(!d.supplier_id||!d.material_id)throw new Error('Выберите поставщика и материал');return insert('supplier_materials',{...d,unit_price:Number(d.unit_price||0),minimum_order_quantity:Number(d.minimum_order_quantity||0),lead_time_days:Number(d.lead_time_days||0),is_preferred:d.is_preferred==='true',currency:'AED'})});

  employeesPage=function(){return `<div class="cards">${state.employees.map(e=>{const photo=state.employeePhotos[e.id]||(/^https?:|^data:/.test(e.photo_url||'')?e.photo_url:null),initials=e.full_name.split(/\s+/).map(x=>x[0]).join('').slice(0,2).toUpperCase();return `<article class="entity-card" onclick="openEmployee('${e.id}')"><div class="employee-card-head">${photo?`<img class="employee-photo" src="${esc(photo)}" alt="${esc(e.full_name)}">`:`<div class="employee-photo">${esc(initials)}</div>`}<div><h3>${esc(e.full_name)}</h3><p>${esc(e.job_title||'Сотрудник')} · ${esc(e.department||'Без отдела')}</p></div></div><div class="card-meta section-gap"><span class="tag">${esc(e.payment_type)}</span><span class="tag">${money(e.monthly_salary)} AED</span><span class="tag">${esc(e.phone||'Нет телефона')}</span></div></article>`}).join('')||'<div class="panel empty">Сотрудников пока нет</div>'}</div>`};
  async function uploadEmployeePhoto(file){if(!file?.size)return null;if(file.size>5*1024*1024)throw new Error('Фотография больше 5 MB');const path=`employees/${crypto.randomUUID()}-${file.name.replace(/[^a-zA-Z0-9._-]/g,'_')}`;const res=await fetch(SUPABASE_URL+'/storage/v1/object/company-files/'+path.split('/').map(encodeURIComponent).join('/'),{method:'POST',headers:{apikey:SUPABASE_KEY,Authorization:'Bearer '+state.session.access_token,'Content-Type':file.type||'image/jpeg','x-upsert':'true'},body:file});if(!res.ok)throw new Error('Не удалось загрузить фотографию');return path}
  function employeeForm(e={}){return `<label class="full">Фотография сотрудника<input name="photo" type="file" accept="image/png,image/jpeg,image/webp"></label>`+input('full_name','Имя','text',e.full_name||'','required')+input('employee_number','Номер сотрудника','text',e.employee_number||'')+input('job_title','Должность','text',e.job_title||'')+input('department','Отдел','text',e.department||'')+input('phone','Телефон','text',e.phone||'')+input('start_date','Дата начала','date',e.start_date||'')+select('payment_type','Тип оплаты',`<option value="monthly" ${e.payment_type==='monthly'?'selected':''}>Месячная</option><option value="daily" ${e.payment_type==='daily'?'selected':''}>Дневная</option><option value="hourly" ${e.payment_type==='hourly'?'selected':''}>Почасовая</option><option value="project" ${e.payment_type==='project'?'selected':''}>За проект / чертежи</option>`)+input('monthly_salary','Месячная зарплата','number',e.monthly_salary||0)+input('daily_rate','Дневная ставка','number',e.daily_rate||0)+input('hourly_rate','Почасовая ставка','number',e.hourly_rate||0)+input('overtime_rate','Overtime ставка','number',e.overtime_rate||0)+input('project_rate','Ставка за проект','number',e.project_rate||0)}
  const employeeRecord14=(d,photo)=>({full_name:d.full_name,employee_number:d.employee_number||null,job_title:d.job_title||null,department:d.department||null,phone:d.phone||null,start_date:d.start_date||null,payment_type:d.payment_type,monthly_salary:Number(d.monthly_salary||0),daily_rate:Number(d.daily_rate||0),hourly_rate:Number(d.hourly_rate||0),overtime_rate:Number(d.overtime_rate||0),project_rate:Number(d.project_rate||0),photo_url:photo||null});
  openEmployeeModal=function(){openModal('Новый сотрудник',employeeForm({payment_type:'monthly'}),async d=>insert('employees',employeeRecord14(d,await uploadEmployeePhoto(d.photo))))};
  function openEmployeeEdit14(id){const e=state.employees.find(x=>x.id===id);openModal('Изменить сотрудника',employeeForm(e),async d=>update('employees',id,employeeRecord14(d,(await uploadEmployeePhoto(d.photo))||e.photo_url)))}
  window.openEmployee=id=>{baseOpenEmployee(id);const e=state.employees.find(x=>x.id===id),photo=state.employeePhotos[id]||(/^https?:|^data:/.test(e?.photo_url||'')?e.photo_url:null);if(photo)$('#drawerContent')?.insertAdjacentHTML('afterbegin',`<img src="${esc(photo)}" alt="${esc(e.full_name)}" style="width:110px;height:110px;border-radius:18px;object-fit:cover;margin-bottom:16px">`)};
  window.editRecord=(type,id)=>{if(type==='material')return openMaterialEdit14(id);if(type==='employee')return openEmployeeEdit14(id);return baseEditRecord(type,id)};

  function period(){return state.payrollPeriods.find(p=>Number(p.period_year)===state.payrollYear&&Number(p.period_month)===state.payrollMonth)}
  payrollPage=function(){const p=period(),entries=p?state.payrollEntries.filter(x=>x.payroll_period_id===p.id):[],events=state.attendanceEvents.filter(x=>new Date(x.event_date).getFullYear()===state.payrollYear&&new Date(x.event_date).getMonth()+1===state.payrollMonth);const tabs=[['summary','Сводка'],['journal','Журнал'],['calendar','Календарь'],['design','Чертёжники по проектам']];let body='';
    if(state.payrollTab==='summary'){const accrued=entries.reduce((a,x)=>a+Number(x.accrued||0),0),adv=entries.reduce((a,x)=>a+Number(x.advances||0),0),paid=entries.reduce((a,x)=>a+Number(x.paid||0),0),balance=entries.reduce((a,x)=>a+Number(x.balance||0),0);body=`<div class="kpis">${metric('banknote','Начислено',money(accrued)+' AED','за месяц')}${metric('wallet','Авансы',money(adv)+' AED','выдано')}${metric('check-square','Выплачено',money(paid)+' AED','закрытые выплаты')}${metric('clock','Остаток',money(balance)+' AED','к выплате')}</div><div class="panel">${table(['СОТРУДНИК','БАЗА','OVERTIME','ОТСУТСТВИЕ','АВАНС','НАЧИСЛЕНО','ОСТАТОК'],entries.map(x=>[employeeLabel(x.employee_id),money(Number(x.base_amount)+Number(x.daily_amount)+Number(x.hourly_amount)),money(x.overtime_amount),money(x.absence_deduction),money(x.advances),money(x.accrued)+' AED','<b>'+money(x.balance)+' AED</b>']))}</div>`}
    if(state.payrollTab==='journal'){body=`<div class="toolbar panel"><button class="btn primary" onclick="openAttendanceEvent()">＋ Событие</button><span class="tag event-overtime">Overtime</span><span class="tag event-absence">Отсутствие</span><span class="tag event-advance">Аванс</span></div><div class="panel section-gap">${table(['ДАТА','СОТРУДНИК','ТИП','КОЛ-ВО','СТАВКА','СУММА','ПРОЕКТ','ПРИМЕЧАНИЕ'],events.map(x=>[date(x.event_date),employeeLabel(x.employee_id),eventName(x.event_type),Number(x.quantity),money(x.rate),`<b>${money(x.amount)} AED</b>`,projectLabel(x.project_id),esc(x.notes||'—')]))}</div>`}
    if(state.payrollTab==='calendar'){const days=daysInMonth(new Date(state.payrollYear,state.payrollMonth-1,1));body=`<div class="panel table-wrap"><table class="data-table calendar-table"><thead><tr><th class="employee-col">СОТРУДНИК</th>${Array.from({length:days},(_,i)=>`<th>${i+1}</th>`).join('')}</tr></thead><tbody>${state.employees.map(e=>`<tr><td class="employee-col"><b>${esc(e.full_name)}</b></td>${Array.from({length:days},(_,i)=>{const day=i+1,ev=events.filter(x=>x.employee_id===e.id&&new Date(x.event_date).getDate()===day);return `<td title="${esc(ev.map(x=>eventName(x.event_type)+' '+x.quantity).join(', ')||'Присутствует')}">${ev.map(x=>`<span class="status event-${x.event_type}">${x.event_type==='overtime'?'OT':x.event_type==='absence'?'A':'ADV'}</span>`).join('')||'·'}</td>`}).join('')}</tr>`).join('')}</tbody></table></div>`}
    if(state.payrollTab==='design'){const total=state.designCompensations.reduce((a,x)=>a+Number(x.final_payment||0),0);body=`<div class="kpis">${metric('id-card','Проектных расчётов',state.designCompensations.length,'SketchUp / Revit / Базис')}${metric('money','К выплате',money(total)+' AED','включая материал-бонус')}${metric('layers','Программ',state.designPrograms.length,'отдельные расчёты')}${metric('settings','Правил',state.designRules.length,'редактируемая модель')}</div><div class="toolbar panel"><button class="btn primary" onclick="openDesignCompensation()">＋ Проектный расчёт</button></div><div class="panel section-gap">${table(['ПРОЕКТ','ПОМЕЩЕНИЕ','ЧЕРТЁЖНИК','ПРОГРАММЫ','МАТЕРИАЛЫ','БОНУС','К ВЫПЛАТЕ','СТАТУС'],state.designCompensations.map(c=>{const programs=state.designPrograms.filter(x=>x.compensation_id===c.id);return [`<button class="btn" onclick="openDesignCompensation('${c.id}')">${esc(c.project_number||projectLabel(c.project_id))}</button>`,esc(c.room_type||'—'),esc(c.designer_name||employeeLabel(c.designer_id)),programs.map(x=>programName(x.program)+' '+money(x.total_amount)).join('<br>'),money(c.material_total),money(c.material_bonus),`<b>${money(c.final_payment)} AED</b>`,esc(c.status)]}))}</div>`}
    return `<div class="toolbar panel"><select class="field" onchange="setPayrollMonth(this.value)">${Array.from({length:12},(_,i)=>`<option value="${i+1}" ${state.payrollMonth===i+1?'selected':''}>${new Intl.DateTimeFormat('ru',{month:'long'}).format(new Date(2026,i,1))}</option>`).join('')}</select><select class="field" onchange="setPayrollYear(this.value)">${[state.payrollYear-1,state.payrollYear,state.payrollYear+1].map(y=>`<option ${state.payrollYear===y?'selected':''}>${y}</option>`).join('')}</select><button class="btn" onclick="calculatePayroll()">Пересчитать</button><div class="payroll-tabs">${tabs.map(([v,n])=>`<button class="btn ${state.payrollTab===v?'primary':''}" onclick="setPayrollTab('${v}')">${n}</button>`).join('')}</div></div><div class="section-gap">${body}</div>`};
  const table=(heads,rows)=>`<div class="table-wrap"><table class="data-table"><thead><tr>${heads.map(x=>`<th>${x}</th>`).join('')}</tr></thead><tbody>${rows.map(r=>`<tr>${r.map(x=>`<td>${x??'—'}</td>`).join('')}</tr>`).join('')||`<tr><td colspan="${heads.length}" class="empty">Нет данных</td></tr>`}</tbody></table></div>`;
  const eventName=t=>({absence:'Отсутствие',overtime:'Overtime',advance:'Аванс'}[t]||t),programName=t=>({sketchup:'SketchUp',revit:'Revit',basis:'Базис-Мебельщик'}[t]||t);
  window.setPayrollTab=t=>{state.payrollTab=t;renderPage()};
  window.openAttendanceEvent=()=>openModal('Событие зарплаты',select('employee_id','Сотрудник','<option value="">Выберите</option>'+opts(state.employees,'id','full_name'))+select('event_type','Тип','<option value="overtime">Overtime · часы</option><option value="absence">Отсутствие · часы</option><option value="advance">Аванс · AED</option>')+input('event_date','Дата','date',new Date().toISOString().slice(0,10))+input('quantity','Часы или сумма','number','0','required step="0.01" min="0"')+select('project_id','Проект','<option value="">Без проекта</option>'+opts(state.projects))+`<label class="full">Примечание<textarea name="notes"></textarea></label>`,async d=>{if(!d.employee_id)throw new Error('Выберите сотрудника');return insert('payroll_attendance_events',{employee_id:d.employee_id,event_type:d.event_type,event_date:d.event_date,quantity:Number(d.quantity),project_id:d.project_id||null,notes:d.notes||null})});
  window.openDesignCompensation=id=>{const c=state.designCompensations.find(x=>x.id===id)||{};if(id)return openDesignDrawer(c);openModal('Проектный расчёт чертёжника',select('project_id','Проект','<option value="">Без проекта</option>'+opts(state.projects))+input('project_number','Номер / название проекта')+select('room_type','Помещение','<option value="">Выберите</option>'+opts(groupItems('room_type'),'code','name'))+select('designer_id','Чертёжник','<option value="">Не выбран</option>'+opts(state.employees,'id','full_name'))+input('designer_name','Чертёжник — свободный ввод')+input('start_date','Начало','date')+input('planned_finish_date','Плановое завершение','date')+input('egger_actual_cost','Egger · фактическая стоимость','number','0','step="0.01"')+input('additional_material_cost','Дополнительный материал','number','0','step="0.01"')+input('hardware_cost','Фурнитура','number','0','step="0.01"')+input('repeat_order_error_cost','Повторный заказ из-за ошибок','number','0','step="0.01"')+select('program','Первая программа','<option value="sketchup">SketchUp</option><option value="revit">Revit</option><option value="basis">Базис-Мебельщик</option>')+`<label class="full">Комментарий менеджера<textarea name="manager_comment"></textarea></label>`,async d=>{const rec=await insert('design_compensations',{project_id:d.project_id||null,project_number:d.project_number||null,room_type:local(groupItems('room_type').find(x=>x.code===d.room_type)?.name)||d.room_type||null,designer_id:d.designer_id||null,designer_name:d.designer_name||null,start_date:d.start_date||null,planned_finish_date:d.planned_finish_date||null,egger_actual_cost:Number(d.egger_actual_cost||0),additional_material_cost:Number(d.additional_material_cost||0),hardware_cost:Number(d.hardware_cost||0),repeat_order_error_cost:Number(d.repeat_order_error_cost||0),manager_comment:d.manager_comment||null,status:'new'});await rawApi('/rest/v1/rpc/create_design_program',{method:'POST',body:JSON.stringify({p_compensation_id:rec.id,p_program:d.program})});return rec})};
  function openDesignDrawer(c){const programs=state.designPrograms.filter(x=>x.compensation_id===c.id);$('#drawerNumber').textContent=c.project_number||projectLabel(c.project_id);$('#drawerContent').innerHTML=`<h2 class="drawer-title">Расчёт чертёжника</h2><p class="drawer-sub">${esc(c.designer_name||employeeLabel(c.designer_id))} · ${esc(c.room_type||'—')}</p><div class="detail-grid"><div class="detail-box"><span>Материалы</span><b>${money(c.material_total)} AED</b></div><div class="detail-box"><span>Бонус материалов</span><b>${money(c.material_bonus)} AED</b></div><div class="detail-box"><span>Программы</span><b>${money(c.program_total)} AED</b></div><div class="detail-box"><span>Итого к выплате</span><b>${money(c.final_payment)} AED</b></div></div><div class="action-row"><button class="btn" onclick="addDesignProgram('${c.id}','sketchup')">＋ SketchUp</button><button class="btn" onclick="addDesignProgram('${c.id}','revit')">＋ Revit</button><button class="btn" onclick="addDesignProgram('${c.id}','basis')">＋ Базис</button></div>${programs.map(p=>{const stages=state.designStages.filter(x=>x.program_entry_id===p.id);return `<section class="panel section-gap"><div class="panel-head"><div><h2>${programName(p.program)} · ${money(p.total_amount)} AED</h2><p>Прогресс ${Number(p.progress_percent)}% · правки +${money(p.changes_amount)} · ошибки −${money(p.error_deduction)}</p></div><button class="btn" onclick="editDesignProgram('${p.id}')">Расчёт</button></div><div class="side-list">${stages.map(s=>`<div class="mini-item"><div><b>${esc(local(s.stage_name))}</b><small>${Number(s.weight_percent)}% выплаты</small></div><button class="btn ${s.is_completed?'primary':''}" onclick="toggleDesignStage('${s.id}',${!s.is_completed})">${s.is_completed?'Выполнено':'Отметить'}</button></div>`).join('')}</div></section>`}).join('')||'<div class="empty">Добавьте программу расчёта.</div>'}`;$('#drawerOverlay').classList.add('show');document.body.classList.add('overlay-lock')}
  window.addDesignProgram=async(id,program)=>{await rawApi('/rest/v1/rpc/create_design_program',{method:'POST',body:JSON.stringify({p_compensation_id:id,p_program:program})});await loadAll();openDesignCompensation(id)};
  window.toggleDesignStage=async(id,value)=>{await update('design_stage_entries',id,{is_completed:value,completed_at:value?new Date().toISOString():null});await loadAll();const s=state.designStages.find(x=>x.id===id),p=state.designPrograms.find(x=>x.id===s?.program_entry_id);if(p)openDesignCompensation(p.compensation_id)};
  window.editDesignProgram=id=>{const p=state.designPrograms.find(x=>x.id===id);openModal('Расчёт '+programName(p.program),input('sheet_count','Количество листов','number',p.sheet_count||0,'step="0.01"')+input('sheet_rate','Цена листа','number',p.sheet_rate||0,'step="0.01"')+input('changes_coefficient','Коэффициент правок 0–10','number',p.changes_coefficient||0,'min="0" max="10"')+input('errors_coefficient','Коэффициент ошибок 0–10','number',p.errors_coefficient||0,'min="0" max="10"')+`<div class="full warning-box">Правки: коэффициент × 40 AED. Ошибки: коэффициент × 30 AED. Формулы загружены из вашей Excel-таблицы.</div>`,async d=>{await update('design_program_entries',id,{sheet_count:Number(d.sheet_count||0),sheet_rate:Number(d.sheet_rate||0),changes_coefficient:Number(d.changes_coefficient||0),errors_coefficient:Number(d.errors_coefficient||0)});return rawApi('/rest/v1/rpc/recalculate_design_program',{method:'POST',body:JSON.stringify({p_program_entry_id:id})})})};

  settingsPage=function(){const original=baseSettings();return original+`<div class="section-title section-gap"><div><h2>Библиотеки материалов и снабжения</h2><p>Категория → подкатегория → материал → бренд → поставщик. Названия отображаются корректно, без [object Object].</p></div></div><div class="dictionary-grid"><section class="panel"><div class="panel-head"><div><h2>Категории и подкатегории</h2><p>${state.materialCategories.length} категорий · ${state.materialSubcategories.length} подкатегорий</p></div></div><div class="library-list">${state.materialCategories.map(c=>`<span class="library-chip"><b>${esc(local(c.name))}</b> · ${state.materialSubcategories.filter(s=>s.category_id===c.id).length}</span>`).join('')}</div></section><section class="panel"><div class="panel-head"><div><h2>Бренды</h2><p>Готовая библиотека для выбора материала</p></div><button class="btn" onclick="openBrandModal()">＋</button></div><div class="library-list">${state.brands.map(b=>`<span class="library-chip">${esc(b.name)}</span>`).join('')}</div></section><section class="panel"><div class="panel-head"><div><h2>Поставщики материалов</h2><p>Используются в материале и управлении снабжением</p></div><button class="btn" onclick="openSupplierModal()">＋</button></div><div class="library-list">${state.suppliers.map(s=>`<span class="library-chip">${esc(s.name)}</span>`).join('')||'<span class="muted">Нет поставщиков</span>'}</div></section><section class="panel"><div class="panel-head"><div><h2>Правила зарплат</h2><p>30 дней · 10 часов · присутствие по умолчанию</p></div></div><div class="finance-summary"><div class="summary-line"><span>Делитель месячной зарплаты</span><b>${state.payrollSettings[0]?.salary_day_divisor||30}</b></div><div class="summary-line"><span>Рабочих часов в дне</span><b>${state.payrollSettings[0]?.hours_per_day||10}</b></div><div class="summary-line"><span>События журнала</span><b>Отсутствие · OT · Аванс</b></div></div></section></div>`};
  window.openBrandModal=()=>openModal('Новый бренд',input('name','Название','text','','required')+input('website_url','Сайт','url')+`<label class="full">Комментарий<textarea name="notes"></textarea></label>`,d=>insert('material_brands',d));
  openExpenseModal=function(){openModal('Новый расход',select('project_id','Проект','<option value="">Общий расход</option>'+opts(state.projects))+select('category','Категория расходов',opts(groupItems('expense_category'),'code','name'))+input('subcategory','Подкатегория')+input('description','Описание','text','','required')+input('actual_amount','Сумма, AED','number','0','required step="0.01"')+input('expense_date','Дата','date',new Date().toISOString().slice(0,10))+select('payment_status','Статус оплаты','<option value="unpaid">Не оплачено</option><option value="paid">Оплачено</option>'),async d=>insert('expenses',{...d,project_id:d.project_id||null,actual_amount:Number(d.actual_amount||0)}))};

  renderPage=function(){if(state.page==='suppliers')$('#content').innerHTML=suppliersPage();else baseRenderPage();if(state.page==='procurement'){const host=$('#content');host.insertAdjacentHTML('afterbegin',`<div class="procurement-tabs"><button class="btn primary">Заявки и заказы</button><button class="btn" onclick="setPage('suppliers')">Поставщики</button><button class="btn" onclick="openSupplierMaterialModal()">Материалы поставщиков</button></div>`)}paintIcons()};
  actionForPage=function(){if(state.page==='suppliers')return openSupplierModal();if(state.page==='payroll'){if(state.payrollTab==='journal')return openAttendanceEvent();if(state.payrollTab==='design')return openDesignCompensation()}return baseAction()};
  $('#pageAction').onclick=actionForPage;
  $$('.nav-btn').forEach(b=>b.onclick=()=>setPage(b.dataset.page));
  paintIcons();
  if(state.session?.access_token)setTimeout(()=>loadAll().catch(e=>toast(e.message)),0);else{updateShell();renderPage()}
})();
