(function(){
  const MODULES={
    estimates:{title:'Сметы',icon:'▤',action:'Новая смета',description:'BOQ, согласование, клиентский доступ, план‑факт и контроль бюджета.',prefix:'EST',types:[['estimate','Смета'],['template','Шаблон сметы'],['revision','Версия сметы']],features:[['Структура BOQ','Разделы, подразделы, работы, материалы, себестоимость, цена продажи и маржа.'],['Согласование','Черновик, проверка, клиентские комментарии, утверждение позиций и история версий.'],['План → факт','Материалы, работы, зарплаты, подрядчики, транспорт, разрешения и изменения клиента.'],['Импорт и экспорт','Подготовлено для Excel, CSV, Гранд‑Смета, Smeta.ru, PDF и клиентской ссылки.'],['Автоматизация','После утверждения создаются этапы, задачи, закупки, резервы и финансовый план.'],['Контроль бюджета','Бюджет, потрачено, осталось, прогноз, экономия и перерасход с цветовой индикацией.']]},
    work_schedule:{title:'График работ',icon:'▥',action:'Новый график',description:'Планирование сроков, зависимости, Гант, план‑факт и доступ клиента.',prefix:'SCH',types:[['schedule','График проекта'],['milestone','Контрольная точка'],['template','Шаблон графика']],features:[['Структура','Этап → подэтап → вид работ → задача → контрольная точка.'],['Зависимости','FS, SS, FF и SF, лаги, критический путь и предупреждения о сдвигах.'],['План‑факт','Базовые и текущие даты, фактический прогресс, задержки и прогноз завершения.'],['Исполнители','Прорабы, сотрудники, подрядчики, бригады и их нагрузка.'],['Клиент и подрядчик','Ограниченный доступ, комментарии, согласование и подтверждение сроков.'],['Экспорт','Таблица, Гант, PDF, Excel и история всех изменений.']]},
    financial_accounting:{title:'Финансовый учёт',icon:'◉',action:'Новая операция',description:'Счета компании, денежные операции, подотчёт, счета и финансовый календарь.',prefix:'FIN',types:[['transaction','Финансовая операция'],['account','Счёт компании'],['bill_payable','Счёт к оплате'],['bill_receivable','Счёт к получению'],['employee_advance','Подотчёт']],features:[['Счета','Банк, касса, карты, депозиты, кредиты, валюты и подотчётные счета.'],['Журнал операций','Доходы, расходы, переводы, статьи, проекты, контрагенты, НДС и документы.'],['Подотчёт','Выдача денег, чеки, проверка расходов, возврат остатка и связь с проектом.'],['Банк и 1С','Импорт Excel/CSV, банковская сверка и подготовка интеграции с 1С.'],['Платёжный календарь','Счета к оплате и получению, срочные платежи и уведомления.'],['Аналитика','Остатки, Cash Flow, план‑факт, валютные операции и проектные финансы.']]},
    procurement:{title:'Управление снабжением',icon:'⇄',action:'Новая заявка',description:'Заявки, проверка склада, согласование бюджета, цены, заказы и поставки.',prefix:'PR',types:[['request','Заявка на закупку'],['rfq','Запрос цен'],['supplier_quote','Предложение поставщика'],['purchase_order','Заказ поставщику'],['delivery','Поставка']],features:[['Автозаявки','Из сметы, задачи, графика, контроля стройки, минимального остатка или вручную.'],['Проверка склада','Фактический остаток, резерв, доступно и закупка только недостающего объёма.'],['Согласование','Инициатор, закупщик, бюджет, лимиты, история решений и перерасход.'],['Запрос цен','Несколько поставщиков, сравнение цены, сроков, оплаты, рейтинга и доставки.'],['Заказы и партии','Разделение и объединение заявок, частичные поставки и несколько складов.'],['Приёмка','Заказ → поставка → частичная приёмка → складской документ → финансы.']]},
    site_control:{title:'Контроль стройки',icon:'⌂',action:'Новый отчёт',description:'Дневные отчёты прорабов, фото, прогресс, дефекты и заявки на материалы.',prefix:'SR',types:[['daily_report','Ежедневный отчёт'],['defect','Замечание / дефект'],['quality_check','Проверка качества'],['attendance','Присутствие'],['client_report','Отчёт клиенту']],features:[['Мобильный отчёт','Проект, задача, процент, статус, комментарий, проблема, фото и видео.'],['Подтверждение работ','Прораб завершает, менеджер проверяет, возвращает или подтверждает прогресс.'],['Фото и видео','Хронология по проекту, этапу, помещению, задаче и дате.'],['Дефекты и качество','Журнал замечаний, ответственные, сроки и чек‑листы плитки, покраски, мебели.'],['Материалы','Заявка прораба автоматически переходит в управление снабжением.'],['Telegram','Подготовлена модель для команд, голосовых отчётов и ежедневных напоминаний.']]},
    rate_catalog:{title:'Справочник расценок',icon:'≋',action:'Новая расценка',description:'Конструктор работ, материалов, трудозатрат, механизмов и технологических операций.',prefix:'RATE',types:[['work_rate','Работа'],['material_rate','Материал'],['labor_rate','Труд'],['equipment_rate','Механизм'],['operation','Технологическая операция'],['contractor_rate','Подрядная работа']],features:[['Папки','Мебель, fit‑out, строительство, дизайн, инженерия, монтаж, логистика и сервис.'],['Карточка расценки','Код, тип, единица, себестоимость, продажа, наценка, валюта и срок действия.'],['Технологические операции','Комплект работ, материалов, труда, механизмов, отходов и коэффициентов.'],['Контрагенты','Поставщики и подрядчики, цены, история заказов, рейтинг и документы.'],['Импорт / экспорт','Excel с предпросмотром, сопоставлением колонок, валютой и обработкой дублей.'],['Конструктор сметы','Выбор операции, объёма, брендов, поставщика, подрядчика и наценки.']]},
    management_reports:{title:'Управленческие отчёты',icon:'◫',action:'Сохранить снимок',description:'P&L, Cash Flow, взаиморасчёты, план‑факт, прибыльность и сроки.',prefix:'RPT',types:[['pnl','P&L'],['cash_flow','Cash Flow'],['settlements','Взаиморасчёты'],['project_plan_fact','План‑факт проекта'],['warehouse_report','Склад'],['deadline_report','Сроки']],features:[['P&L','Доходы, прямые и операционные расходы, валовая, операционная и чистая прибыль.'],['Cash Flow','Операционная, инвестиционная и финансовая деятельность плюс прогноз.'],['Взаиморасчёты','Клиенты, поставщики, подрядчики, дебиторская и кредиторская задолженность.'],['Проекты','Финансы, сроки, отклонения, маржа, направления бизнеса и отделы.'],['Детализация','От показателя до проекта, операции, документа, чека или складского движения.'],['Конструктор','Поля, группировки, фильтры, диаграммы, PDF, Excel и автоматическая рассылка.']]},
    warehouse_accounting:{title:'Складской учёт',icon:'▦',action:'Новый документ',description:'Приёмка, резерв, выдача, возврат, перемещение, списание и инвентаризация.',prefix:'GRN',types:[['receipt','Поступление'],['issue','Выдача'],['reserve','Резерв'],['return','Возврат'],['transfer','Перемещение'],['writeoff','Списание'],['inventory','Инвентаризация']],features:[['Несколько складов','Основной, мебельный, объект, производство, автомобиль, брак и возвраты.'],['Адресное хранение','Склад → зона → стеллаж → полка → ячейка; детализация необязательна.'],['Приёмка','По заказу снабжения, частичные поставки, партии, повреждения, фото и документы.'],['Движение','Оприходование, резерв, выдача, возврат, перемещение, списание и обратные операции.'],['Партии и инструменты','Серии, оттенки, сроки годности, оборудование, выдача и ремонт.'],['Контроль','Факт, резерв, доступно, в пути, прогноз, минимум, QR и автоматические заявки.']]}
  };

  Object.assign(state,{moduleRecords:[],moduleLines:[],moduleApprovals:[],moduleHistory:[],warehouseDocuments:[],warehouseDocumentItems:[],reservations:[],batches:[],tools:[],stocktakes:[]});
  Object.entries(MODULES).forEach(([key,m])=>pageMeta[key]=[m.title,m.action]);

  const baseLoadAll=loadAll,baseRenderPage=renderPage,baseSetPage=setPage,baseUpdateShell=updateShell,baseAction=actionForPage;
  const moduleRecords=code=>state.moduleRecords.filter(x=>x.module_code===code&&!x.deleted_at&&!x.archived_at);
  const recordLines=id=>state.moduleLines.filter(x=>x.record_id===id);
  const statusName=s=>({draft:'Черновик',review:'На проверке',sent_to_client:'Отправлена клиенту',changes_required:'Требуются изменения',agreed:'Согласована',approved:'Утверждена',archive:'Архив',active:'Активно',completed:'Завершено',pending:'Ожидает',submitted:'Отправлено',pending_approval:'Ожидает согласования',ordered:'Заказано',partially_delivered:'Частично доставлено',delivered:'Доставлено',open:'Открыто',closed:'Закрыто',overdue:'Просрочено',posted:'Проведён',in_transit:'В пути'}[s]||s||'—');
  const recordTypeName=(m,t)=>MODULES[m]?.types.find(x=>x[0]===t)?.[1]||t||'—';
  const percent=(a,b)=>b?Math.round(Number(a||0)/Number(b)*100):0;
  const stockSummary=materialId=>{const rows=state.stock.filter(x=>x.material_id===materialId),on=rows.reduce((a,x)=>a+Number(x.quantity_on_hand||0),0),reserved=rows.reduce((a,x)=>a+Number(x.reserved||0),0),value=rows.reduce((a,x)=>a+Number(x.inventory_value||0),0);return {on,reserved,available:on-reserved,value}};
  const metric=(icon,label,value,note)=>kpi(icon,label,value,note);

  loadAll=async function(){
    await baseLoadAll();
    const rows=await Promise.all([
      safeLoad('/rest/v1/module_records?select=*&deleted_at=is.null&archived_at=is.null&order=updated_at.desc'),
      safeLoad('/rest/v1/module_record_lines?select=*&order=sort_order.asc,created_at.asc'),
      safeLoad('/rest/v1/module_approvals?select=*&order=created_at.desc&limit=250'),
      safeLoad('/rest/v1/module_history?select=*&order=created_at.desc&limit=500'),
      safeLoad('/rest/v1/warehouse_documents?select=*&order=document_date.desc&limit=250'),
      safeLoad('/rest/v1/warehouse_document_items?select=*&order=created_at.desc&limit=500'),
      safeLoad('/rest/v1/stock_reservations?select=*&order=created_at.desc&limit=500'),
      safeLoad('/rest/v1/material_batches?select=*&order=created_at.desc&limit=500'),
      safeLoad('/rest/v1/tools_equipment?select=*&order=updated_at.desc&limit=500'),
      safeLoad('/rest/v1/stocktakes?select=*&order=created_at.desc&limit=100')
    ]);
    [state.moduleRecords,state.moduleLines,state.moduleApprovals,state.moduleHistory,state.warehouseDocuments,state.warehouseDocumentItems,state.reservations,state.batches,state.tools,state.stocktakes]=rows;
    updateShell();renderPage();
  };

  function canOpenModule(code){const r=state.profile?.role;if(['owner','admin'].includes(r))return true;const map={accountant:['estimates','financial_accounting','procurement','rate_catalog','management_reports','warehouse_accounting','tasks'],project_manager:Object.keys(MODULES).concat('tasks'),foreman:['work_schedule','procurement','site_control','warehouse_accounting','tasks'],designer:['estimates','work_schedule','tasks'],procurement:['estimates','work_schedule','procurement','rate_catalog','warehouse_accounting','tasks'],storekeeper:['procurement','warehouse_accounting','tasks'],marketing:['tasks'],employee:['site_control','tasks']};return (map[r]||[]).includes(code)}
  updateShell=function(){baseUpdateShell();Object.keys(MODULES).forEach(code=>{const el=document.querySelector(`[data-module-count="${code}"]`);if(el)el.textContent=code==='warehouse_accounting'?state.warehouseDocuments.length:moduleRecords(code).length});$('#ribbonTasksCount').textContent=state.tasks.filter(x=>x.status!=='completed').length;$$('[data-module-page]').forEach(b=>b.classList.toggle('hidden',!canOpenModule(b.dataset.modulePage)));syncRibbon()};
  function syncRibbon(){const page=state.page==='warehouse'?'warehouse_accounting':state.page;$$('[data-module-page]').forEach(b=>b.classList.toggle('active',b.dataset.modulePage===page));document.querySelector('[data-module-page].active')?.scrollIntoView({block:'nearest',inline:'nearest'})}
  setPage=function(page){if(MODULES[page]&&!canOpenModule(page))page='dashboard';baseSetPage(page);syncRibbon()};

  function moduleHero(code){const m=MODULES[code],count=moduleRecords(code).length;return `<div class="module-hero"><div><h2>${m.icon} ${m.title}</h2><p>${m.description}</p><div class="card-meta"><span class="tag">${count} записей</span><span class="tag">Связано с проектами и облаком</span><span class="tag">RU · готово к EN</span></div></div><button class="btn" onclick="openModuleCreate('${code}')">＋ ${m.action}</button></div>`}
  function featurePanel(code){return `<section class="panel section-gap"><div class="panel-head"><div><h2>Возможности модуля</h2><p>Все переданные требования сохранены в архитектуре Phase 1.3</p></div></div><div class="module-feature-grid">${MODULES[code].features.map(x=>`<div class="module-feature"><b>${x[0]}</b><p>${x[1]}</p></div>`).join('')}</div></section>`}
  function emptyModule(code){return `<div class="panel module-empty"><b>Модуль готов к первым данным</b><p>${MODULES[code].description} Создайте первую запись; она сохранится в Supabase и появится на всех устройствах.</p><button class="btn primary" onclick="openModuleCreate('${code}')">＋ ${MODULES[code].action}</button></div>`}
  function moduleTable(code,records=moduleRecords(code)){return records.length?`<div class="panel">${simpleTable(['НОМЕР','ТИП','НАЗВАНИЕ','ПРОЕКТ','СТАТУС','ПЛАН','ФАКТ','СРОК'],records.map(r=>[`<button class="btn" onclick="openModuleRecord('${r.id}')">${esc(r.record_number||'БЕЗ НОМЕРА')}</button>`,esc(recordTypeName(code,r.record_type)),`<b>${esc(r.name)}</b>`,esc(projectName(r.project_id)),`<span class="status ${statusTone(r.status)}">${esc(statusName(r.status))}</span>`,money(r.planned_amount)+' '+esc(r.currency),money(r.actual_amount)+' '+esc(r.currency),date(r.planned_finish)]))}</div>`:emptyModule(code)}
  function modulePage(code){const records=moduleRecords(code),planned=records.reduce((a,x)=>a+Number(x.planned_amount||0),0),actual=records.reduce((a,x)=>a+Number(x.actual_amount||0),0),overdue=records.filter(x=>x.planned_finish&&new Date(x.planned_finish)<new Date()&&!['approved','completed','closed','archive'].includes(x.status)).length;return moduleHero(code)+`<div class="module-summary">${metric('▣','Записей',records.length,'в модуле')}${metric('AED','План',money(planned),'AED')}${metric('◒','Факт',money(actual),'AED')}${metric('!','Просрочено',overdue,'требуют внимания')}</div><div class="section-gap">${moduleTable(code,records)}</div>`+featurePanel(code)}

  function estimatesPage(){const rs=moduleRecords('estimates'),approved=rs.filter(x=>['agreed','approved'].includes(x.status)),sale=rs.reduce((a,x)=>a+Number(x.sale_amount||0),0),cost=rs.reduce((a,x)=>a+Number(x.cost_amount||0),0);return moduleHero('estimates')+`<div class="module-summary">${metric('▤','Смет',rs.length,'все версии')}${metric('✓','Согласовано',approved.length,'с клиентом')}${metric('AED','Цена продажи',money(sale),'AED')}${metric('%','Плановая маржа',sale?Math.round((sale-cost)/sale*100):0,'%')}</div><div class="section-gap">${moduleTable('estimates',rs)}</div>`+featurePanel('estimates')}
  function schedulePage(){const rs=moduleRecords('work_schedule'),lines=rs.flatMap(r=>recordLines(r.id)),late=lines.filter(x=>x.planned_finish&&new Date(x.planned_finish)<new Date()&&x.progress<100);return moduleHero('work_schedule')+`<div class="module-summary">${metric('▥','Графиков',rs.length,'версии проектов')}${metric('≋','Работ',lines.length,'этапы и задачи')}${metric('!','Задержки',late.length,'работ')}${metric('%','Средний прогресс',lines.length?Math.round(lines.reduce((a,x)=>a+Number(x.progress||0),0)/lines.length):0,'%')}</div><div class="section-gap">${moduleTable('work_schedule',rs)}</div><div class="section-gap">${ganttPage()}</div>`+featurePanel('work_schedule')}
  function financePage(){const rs=moduleRecords('financial_accounting'),income=state.payments.filter(x=>x.direction==='income'&&x.status==='paid').reduce((a,x)=>a+Number(x.amount||0),0),expense=state.expenses.reduce((a,x)=>a+Number(x.actual_amount||0),0),urgent=rs.filter(x=>x.data?.is_urgent&&x.status!=='closed').length;return moduleHero('financial_accounting')+`<div class="module-summary">${metric('↑','Получено',money(income),'AED')}${metric('↓','Расходы',money(expense),'AED')}${metric('AED','Денежный результат',money(income-expense),'AED')}${metric('!','Срочные счета',urgent,'к оплате')}</div><div class="section-gap">${moduleTable('financial_accounting',rs)}</div>`+featurePanel('financial_accounting')}
  function procurementPage(){const rs=moduleRecords('procurement'),requests=rs.filter(x=>x.record_type==='request'),orders=rs.filter(x=>x.record_type==='purchase_order'),late=rs.filter(x=>x.planned_finish&&new Date(x.planned_finish)<new Date()&&!['delivered','closed'].includes(x.status));return moduleHero('procurement')+`<div class="module-summary">${metric('⇄','Заявок',requests.length,'в снабжении')}${metric('▣','Заказов',orders.length,'поставщикам')}${metric('◷','В пути',rs.filter(x=>['ordered','in_transit','partially_delivered'].includes(x.status)).length,'поставок')}${metric('!','Задержки',late.length,'позиций')}</div><div class="section-gap">${moduleTable('procurement',rs)}</div>`+featurePanel('procurement')}
  function sitePage(){const rs=moduleRecords('site_control'),reports=rs.filter(x=>x.record_type==='daily_report'),issues=rs.filter(x=>x.record_type==='defect'),openIssues=issues.filter(x=>!['closed','approved'].includes(x.status));return moduleHero('site_control')+`<div class="module-summary">${metric('⌂','Отчётов',reports.length,'с объектов')}${metric('◉','Сегодня',reports.filter(x=>x.planned_start===new Date().toISOString().slice(0,10)).length,'отчётов')}${metric('!','Замечания',openIssues.length,'открыто')}${metric('%','Прогресс',reports.length?Math.round(reports.reduce((a,x)=>a+Number(x.progress||0),0)/reports.length):0,'%')}</div><div class="section-gap">${moduleTable('site_control',rs)}</div>`+featurePanel('site_control')}
  function ratesPage(){const rs=moduleRecords('rate_catalog'),sale=rs.reduce((a,x)=>a+Number(x.sale_amount||0),0),cost=rs.reduce((a,x)=>a+Number(x.cost_amount||0),0);return moduleHero('rate_catalog')+`<div class="module-summary">${metric('≋','Расценок',rs.length,'в справочнике')}${metric('▦','Операций',rs.filter(x=>x.record_type==='operation').length,'комплексных')}${metric('AED','Средняя продажа',money(rs.length?sale/rs.length:0),'AED')}${metric('%','Средняя маржа',sale?Math.round((sale-cost)/sale*100):0,'%')}</div><div class="section-gap">${moduleTable('rate_catalog',rs)}</div>`+featurePanel('rate_catalog')}
  function reportsPage(){const income=state.payments.filter(x=>x.direction==='income'&&x.status==='paid').reduce((a,x)=>a+Number(x.amount||0),0),expenses=state.expenses.reduce((a,x)=>a+Number(x.actual_amount||0),0),receivable=state.payments.filter(x=>x.direction==='income'&&x.status!=='paid').reduce((a,x)=>a+Number(x.amount||0),0),inventory=state.materials.reduce((a,m)=>a+stockSummary(m.id).value,0),margin=income?Math.round((income-expenses)/income*100):0;return moduleHero('management_reports')+`<div class="module-summary">${metric('AED','Доходы',money(income),'AED')}${metric('↓','Расходы',money(expenses),'AED')}${metric('%','Маржа',margin,'%')}${metric('◷','Дебиторка',money(receivable),'AED')}</div><div class="split-grid section-gap"><section class="panel"><div class="panel-head"><div><h2>P&L — текущие данные</h2><p>Детализация до проекта и операции</p></div></div><div class="finance-summary"><div class="summary-line"><span>Выручка</span><b>${money(income)} AED</b></div><div class="summary-line"><span>Фактические расходы</span><b>${money(expenses)} AED</b></div><div class="summary-line"><span>Прибыль</span><b>${money(income-expenses)} AED</b></div><div class="summary-line"><span>Маржа</span><b>${margin}%</b></div></div></section><section class="panel"><div class="panel-head"><div><h2>Контроль компании</h2><p>Ключевые взаиморасчёты и активы</p></div></div><div class="finance-summary"><div class="summary-line"><span>Ожидаемые платежи</span><b>${money(receivable)} AED</b></div><div class="summary-line"><span>Стоимость склада</span><b>${money(inventory)} AED</b></div><div class="summary-line"><span>Активные проекты</span><b>${state.projects.filter(x=>x.status!=='Завершён').length}</b></div><div class="summary-line"><span>Просроченные задачи</span><b>${state.tasks.filter(x=>x.due_date&&new Date(x.due_date)<new Date()&&x.status!=='completed').length}</b></div></div></section></div>`+featurePanel('management_reports')}
  function warehouseAccountingPage(){const docs=state.warehouseDocuments,posted=docs.filter(x=>['posted','received'].includes(x.status)),inTransit=docs.filter(x=>x.status==='in_transit'),totalValue=state.materials.reduce((a,m)=>a+stockSummary(m.id).value,0),low=state.materials.filter(m=>stockSummary(m.id).available<=Number(m.minimum_stock||0));const docTable=docs.length?simpleTable(['ДОКУМЕНТ','ТИП','ДАТА','ПРОЕКТ','СТАТУС','СТОИМОСТЬ'],docs.slice(0,100).map(d=>[`<button class="btn" onclick="openWarehouseDocument('${d.id}')">${esc(d.document_number)}</button>`,esc(recordTypeName('warehouse_accounting',d.document_type)),date(d.document_date),esc(projectName(d.project_id)),`<span class="status ${statusTone(d.status)}">${esc(statusName(d.status))}</span>`,money(d.total_cost)+' AED'])):'<div class="empty">Складских документов пока нет</div>';return moduleHero('warehouse_accounting')+`<div class="module-summary">${metric('AED','Стоимость остатков',money(totalValue),'AED')}${metric('▣','Документов',docs.length,'в журнале')}${metric('✓','Проведено',posted.length,'документов')}${metric('!','Ниже минимума',low.length,'материалов')}</div><div class="module-tabs section-gap"><button class="btn primary">Остатки</button><button class="btn">Документы</button><button class="btn">Резервы · ${state.reservations.length}</button><button class="btn">Партии · ${state.batches.length}</button><button class="btn">Инструменты · ${state.tools.length}</button><button class="btn">Инвентаризации · ${state.stocktakes.length}</button><button class="btn">В пути · ${inTransit.length}</button></div>${warehousePage()}<section class="panel section-gap"><div class="panel-head"><div><h2>Складские документы</h2><p>Подтверждённые документы исправляются только отменой или обратной операцией</p></div></div>${docTable}</section>`+featurePanel('warehouse_accounting')}

  renderPage=function(){const map={estimates:estimatesPage,work_schedule:schedulePage,financial_accounting:financePage,procurement:procurementPage,site_control:sitePage,rate_catalog:ratesPage,management_reports:reportsPage,warehouse_accounting:warehouseAccountingPage};if(map[state.page]){$('#content').innerHTML=map[state.page]();syncRibbon()}else{baseRenderPage();syncRibbon()}};

  function moduleStatuses(code){const m={estimates:[['draft','Черновик'],['review','На проверке'],['sent_to_client','Отправлена клиенту'],['changes_required','Требуются изменения'],['agreed','Согласована'],['approved','Утверждена'],['archive','Архив']],work_schedule:[['draft','Черновик'],['review','На проверке'],['approved','Утверждён'],['active','Активный'],['completed','Завершён']],procurement:[['draft','Черновик'],['submitted','Отправлена'],['pending_approval','На согласовании'],['approved','Согласована'],['ordered','Заказано'],['partially_delivered','Частично доставлено'],['delivered','Доставлено'],['closed','Закрыто']],site_control:[['draft','Черновик'],['submitted','Отправлен'],['review','Проверяется'],['approved','Подтверждён'],['changes_required','На исправлении']]}[code]||[['draft','Черновик'],['pending','Ожидает'],['approved','Утверждено'],['active','Активно'],['closed','Закрыто']];return m.map(([v,n])=>`<option value="${v}">${n}</option>`).join('')}
  async function nextNumber(code,type){const m=MODULES[code],prefix=code==='warehouse_accounting'?({issue:'ISSUE',transfer:'TRF',return:'RET',writeoff:'WOFF',inventory:'INV'}[type]||'GRN'):m.prefix;try{return await rawApi('/rest/v1/rpc/next_document_number',{method:'POST',body:JSON.stringify({p_document_type:code+'_'+type,p_prefix:prefix})})}catch{return `${prefix}-${new Date().getFullYear()}-${String(Date.now()).slice(-4)}`}}
  window.openModuleCreate=code=>{if(code==='warehouse_accounting')return openWarehouseDocumentModal();const m=MODULES[code];if(!m)return;const today=new Date().toISOString().slice(0,10),typeOptions=m.types.map(([v,n])=>`<option value="${v}">${n}</option>`).join('');openModal(m.action,select('record_type','Тип записи',typeOptions)+input('name','Название','text','','required')+select('project_id','Проект','<option value="">Без проекта</option>'+optionList(state.projects,'id','name'))+select('client_id','Клиент','<option value="">Без клиента</option>'+optionList(state.clients,'id','name'))+select('responsible_id','Ответственный','<option value="">Не назначен</option>'+optionList(state.profiles,'id','full_name'))+select('status','Статус',moduleStatuses(code))+input('planned_start','Дата начала','date',code==='site_control'?today:'')+input('planned_finish','Плановый срок','date')+input('planned_amount','План / бюджет, AED','number','0','step="0.01"')+input('cost_amount','Себестоимость, AED','number','0','step="0.01"')+input('sale_amount','Цена продажи, AED','number','0','step="0.01"')+input('progress','Прогресс, %','number','0','min="0" max="100"')+input('priority','Приоритет','text','normal')+`<label class="full">Описание / комментарий<textarea name="notes"></textarea></label>`,async d=>{const number=await nextNumber(code,d.record_type);return insert('module_records',{module_code:code,record_type:d.record_type,record_number:number,name:d.name,project_id:d.project_id||null,client_id:d.client_id||null,responsible_id:d.responsible_id||null,status:d.status,priority:d.priority||'normal',planned_start:d.planned_start||null,planned_finish:d.planned_finish||null,planned_amount:Number(d.planned_amount||0),cost_amount:Number(d.cost_amount||0),sale_amount:Number(d.sale_amount||0),progress:Number(d.progress||0),currency:'AED',data:{notes:d.notes||'',created_from:'web'}})})};

  window.openModuleRecord=id=>{const r=state.moduleRecords.find(x=>x.id===id);if(!r)return;const lines=recordLines(id),approvals=state.moduleApprovals.filter(x=>x.record_id===id),history=state.moduleHistory.filter(x=>x.record_id===id),variance=Number(r.actual_amount||0)-Number(r.planned_amount||0);$('#drawerNumber').textContent=r.record_number||recordTypeName(r.module_code,r.record_type);$('#drawerContent').innerHTML=`<h2 class="drawer-title">${esc(r.name)}</h2><p class="drawer-sub">${esc(MODULES[r.module_code]?.title)} · ${esc(projectName(r.project_id))}</p><div class="tabs"><button class="tab active">ОБЗОР</button><button class="tab">ПОЗИЦИИ · ${lines.length}</button><button class="tab">СОГЛАСОВАНИЕ · ${approvals.length}</button><button class="tab">ИСТОРИЯ · ${history.length}</button></div><div class="detail-grid"><div class="detail-box"><span>Тип</span><b>${esc(recordTypeName(r.module_code,r.record_type))}</b></div><div class="detail-box"><span>Статус</span><b>${esc(statusName(r.status))}</b></div><div class="detail-box"><span>План</span><b>${money(r.planned_amount)} ${esc(r.currency)}</b></div><div class="detail-box"><span>Факт</span><b>${money(r.actual_amount)} ${esc(r.currency)}</b></div><div class="detail-box"><span>Отклонение</span><b class="${variance>0?'stock-low':''}">${money(variance)} ${esc(r.currency)}</b></div><div class="detail-box"><span>Прогресс</span><b>${Number(r.progress)||0}%</b></div><div class="detail-box"><span>Начало</span><b>${date(r.planned_start)}</b></div><div class="detail-box"><span>Срок</span><b>${date(r.planned_finish)}</b></div></div><div class="action-row"><button class="btn primary" onclick="openModuleLineCreate('${id}')">＋ Позиция / этап</button><button class="btn" onclick="approveModuleRecord('${id}')">✓ Утвердить</button></div><section class="panel section-gap">${simpleTable(['КОД','ТИП','ПОЗИЦИЯ','КОЛ-ВО','СЕБЕСТОИМОСТЬ','ПРОДАЖА','ПРОГРЕСС'],lines.map(x=>[esc(x.code||'—'),esc(x.line_type),esc(x.name),`${Number(x.quantity)} ${esc(x.unit)}`,money(Number(x.quantity)*Number(x.unit_cost))+' AED',money(Number(x.quantity)*Number(x.unit_sale))+' AED',Number(x.progress)+'%']))}</section><h3>Комментарий</h3><p class="detail-note">${esc(r.data?.notes||'Комментариев пока нет.')}</p>`;$('#drawerOverlay').classList.add('show');document.body.classList.add('overlay-lock')};
  window.openModuleLineCreate=id=>{const r=state.moduleRecords.find(x=>x.id===id);if(!r)return;openModal('Новая позиция / этап',select('line_type','Тип','<option value="section">Раздел</option><option value="subsection">Подраздел</option><option value="work">Работа</option><option value="material">Материал</option><option value="task">Задача</option><option value="milestone">Контрольная точка</option>')+input('code','Код')+input('name','Название','text','','required')+select('material_id','Материал','<option value="">Не выбран</option>'+optionList(state.materials,'id','name'))+input('quantity','Количество','number','1','step="0.001" min="0"')+input('unit','Единица','text','pcs')+input('unit_cost','Себестоимость за единицу','number','0','step="0.01"')+input('unit_sale','Цена продажи за единицу','number','0','step="0.01"')+input('planned_start','Начало','date')+input('planned_finish','Завершение','date')+input('progress','Прогресс, %','number','0','min="0" max="100"')+`<label class="full">Описание<textarea name="description"></textarea></label>`,async d=>insert('module_record_lines',{record_id:id,line_type:d.line_type,code:d.code||null,name:d.name,description:d.description||null,material_id:d.material_id||null,quantity:Number(d.quantity||0),unit:d.unit||'pcs',unit_cost:Number(d.unit_cost||0),unit_sale:Number(d.unit_sale||0),planned_start:d.planned_start||null,planned_finish:d.planned_finish||null,progress:Number(d.progress||0),status:'draft',sort_order:recordLines(id).length+1}))};
  window.approveModuleRecord=async id=>{await update('module_records',id,{status:'approved',approved_at:new Date().toISOString(),approved_by:state.profile?.id});await loadAll();openModuleRecord(id);toast('Запись утверждена и сохранена в истории')};

  window.openWarehouseDocumentModal=()=>{const types=MODULES.warehouse_accounting.types.map(([v,n])=>`<option value="${v}">${n}</option>`).join('');openModal('Новый складской документ',select('document_type','Операция',types)+select('source_warehouse_id','Склад отправления','<option value="">Не выбран</option>'+optionList(state.warehouses,'id','name'))+select('destination_warehouse_id','Склад получения','<option value="">Не выбран</option>'+optionList(state.warehouses,'id','name'))+select('project_id','Проект','<option value="">Без проекта</option>'+optionList(state.projects,'id','name'))+select('supplier_id','Поставщик','<option value="">Без поставщика</option>'+optionList(state.suppliers,'id','name'))+input('document_date','Дата','date',new Date().toISOString().slice(0,10))+input('reason','Основание')+input('reference','Связанный документ')+`<label class="full">Комментарий<textarea name="notes"></textarea></label><div class="full warning-box">Сначала создаётся черновик. После добавления позиций кладовщик проводит документ; проведённые документы нельзя удалить.</div>`,async d=>{const inbound=['receipt','return','inventory'].includes(d.document_type),outbound=['issue','reserve','writeoff'].includes(d.document_type);if(d.document_type==='transfer'&&(!d.source_warehouse_id||!d.destination_warehouse_id))throw new Error('Для перемещения выберите склад отправления и получения');if(inbound&&!d.destination_warehouse_id)throw new Error('Выберите склад получения');if(outbound&&!d.source_warehouse_id)throw new Error('Выберите склад отправления');const n=await nextNumber('warehouse_accounting',d.document_type);return insert('warehouse_documents',{document_number:n,document_type:d.document_type,document_date:new Date(d.document_date).toISOString(),status:'draft',source_warehouse_id:d.source_warehouse_id||null,destination_warehouse_id:d.destination_warehouse_id||null,project_id:d.project_id||null,supplier_id:d.supplier_id||null,reason:d.reason||null,reference:d.reference||null,notes:d.notes||null,responsible_id:state.profile?.id})})};

  window.openWarehouseDocument=id=>{const d=state.warehouseDocuments.find(x=>x.id===id);if(!d)return;const lines=state.warehouseDocumentItems.filter(x=>x.document_id===id),locked=['posted','received','reversed'].includes(d.status);$('#drawerNumber').textContent=d.document_number;$('#drawerContent').innerHTML=`<h2 class="drawer-title">${esc(recordTypeName('warehouse_accounting',d.document_type))}</h2><p class="drawer-sub">${date(d.document_date)} · ${esc(projectName(d.project_id))}</p><div class="detail-grid"><div class="detail-box"><span>Статус</span><b>${esc(statusName(d.status))}</b></div><div class="detail-box"><span>Стоимость</span><b>${money(d.total_cost)} ${esc(d.currency)}</b></div><div class="detail-box"><span>Откуда</span><b>${esc(state.warehouses.find(x=>x.id===d.source_warehouse_id)?.name||'—')}</b></div><div class="detail-box"><span>Куда</span><b>${esc(state.warehouses.find(x=>x.id===d.destination_warehouse_id)?.name||'—')}</b></div><div class="detail-box"><span>Поставщик</span><b>${esc(state.suppliers.find(x=>x.id===d.supplier_id)?.name||'—')}</b></div><div class="detail-box"><span>Основание</span><b>${esc(d.reason||d.reference||'—')}</b></div></div><div class="action-row">${locked?'<div class="success-box">Документ подтверждён и защищён от изменения.</div>':`<button class="btn primary" onclick="openWarehouseDocumentLine('${id}')">＋ Добавить материал</button><button class="btn" onclick="postWarehouseDocument('${id}')">✓ Провести документ</button>`}</div><section class="panel section-gap">${simpleTable(['МАТЕРИАЛ','КОЛ-ВО','ПРИНЯТО','ПОВРЕЖДЕНО','ЕД.','ЦЕНА','ПОЛНАЯ СЕБЕСТОИМОСТЬ'],lines.map(x=>[esc(state.materials.find(m=>m.id===x.material_id)?.name||'—'),Number(x.quantity),Number(x.accepted_quantity),Number(x.damaged_quantity),esc(x.unit),money(x.unit_cost),money(Number(x.quantity)*Number(x.landed_unit_cost||x.unit_cost))+' AED']))}</section><h3>Комментарий</h3><p class="detail-note">${esc(d.notes||'Комментариев пока нет.')}</p>`;$('#drawerOverlay').classList.add('show');document.body.classList.add('overlay-lock')};
  window.openWarehouseDocumentLine=id=>openModal('Материал в складском документе',select('material_id','Материал','<option value="">Выберите материал</option>'+optionList(state.materials,'id','name'))+input('ordered_quantity','Заказано','number','0','step="0.001" min="0"')+input('delivered_quantity','Доставлено','number','0','step="0.001" min="0"')+input('accepted_quantity','Принято','number','0','step="0.001" min="0"')+input('damaged_quantity','Повреждено','number','0','step="0.001" min="0"')+input('missing_quantity','Не доставлено','number','0','step="0.001" min="0"')+input('extra_quantity','Лишнее','number','0','step="0.001" min="0"')+input('quantity','Количество операции','number','1','required step="0.001" min="0.001"')+input('unit','Единица','text','pcs')+input('unit_cost','Закупочная цена','number','0','step="0.01" min="0"')+input('landed_unit_cost','Полная складская цена','number','0','step="0.01" min="0"')+select('condition','Состояние','<option value="new">Новый</option><option value="reusable">Пригоден повторно</option><option value="partially_used">Частично использован</option><option value="damaged">Повреждён</option><option value="inspection">Требует проверки</option><option value="defect">Брак</option>')+`<label class="full">Комментарий<textarea name="notes"></textarea></label>`,async x=>{if(!x.material_id)throw new Error('Выберите материал');return insert('warehouse_document_items',{document_id:id,material_id:x.material_id,ordered_quantity:Number(x.ordered_quantity||0),delivered_quantity:Number(x.delivered_quantity||0),accepted_quantity:Number(x.accepted_quantity||0),damaged_quantity:Number(x.damaged_quantity||0),missing_quantity:Number(x.missing_quantity||0),extra_quantity:Number(x.extra_quantity||0),quantity:Number(x.quantity),unit:x.unit||'pcs',unit_cost:Number(x.unit_cost||0),landed_unit_cost:Number(x.landed_unit_cost||0),condition:x.condition,notes:x.notes||null})});
  window.postWarehouseDocument=async id=>{if(!confirm('Провести документ? После подтверждения позиции нельзя будет изменить или удалить.'))return;await rawApi('/rest/v1/rpc/post_warehouse_document',{method:'POST',body:JSON.stringify({p_document_id:id})});await loadAll();openWarehouseDocument(id);toast('Складской документ проведён, остатки обновлены')};

  actionForPage=function(){if(MODULES[state.page])return openModuleCreate(state.page);return baseAction()};$('#pageAction').onclick=actionForPage;
  $$('[data-module-page]').forEach(b=>b.onclick=()=>setPage(b.dataset.modulePage));
  if(state.session?.access_token)setTimeout(()=>loadAll().catch(e=>toast(e.message)),0);else{updateShell();renderPage()}
})();
