(function(){
  const MODULES=[['estimates','Сметы','calculator'],['work_schedule','График работ','calendar'],['financial_accounting','Финансовый учёт','landmark'],['procurement','Управление снабжением','shopping-cart'],['site_control','Контроль стройки','hard-hat'],['warehouse_accounting','Складской учёт','warehouse'],['tasks','Задачи','check-square'],['gantt','Диаграмма Ганта','gantt'],['projects','Проекты','folder'],['materials','Материалы','layers'],['suppliers','Поставщики','truck'],['rate_catalog','Справочник расценок','book-open'],['employees','Сотрудники','id-card'],['expenses','Расходы','receipt'],['payments','Платежи','wallet'],['payroll','Зарплаты','banknote'],['management_reports','Управленческие отчёты','chart'],['clients','Клиенты','users']];
  const baseRender=renderPage,baseUpdate=updateShell,baseSettings=settingsPage,baseAction=actionForPage;
  state.payrollTab=state.payrollTab||'summary';
  const navSetting=()=>state.settings.find(x=>x.setting_key==='navigation_pins');
  const pinned=()=>Array.isArray(navSetting()?.setting_value?.modules)?navSetting().setting_value.modules:[];
  const visibleModule=code=>!document.querySelector(`.nav-btn[data-page="${code}"]`)?.classList.contains('hidden');
  const moduleCount=code=>code==='tasks'?state.tasks.filter(x=>x.status!=='completed').length:code==='warehouse_accounting'?state.warehouseDocuments.length:(state.moduleRecords||[]).filter(x=>x.module_code===code&&!x.deleted_at&&!x.archived_at).length;
  function copyIcon(el,name){const source=document.querySelector(`.nav-icon[data-icon="${name}"] svg`);if(source)el.innerHTML=source.outerHTML}
  function renderRibbon(){const host=$('#moduleRibbon');if(!host)return;const rows=MODULES.filter(([code])=>pinned().includes(code)&&visibleModule(code));host.innerHTML=rows.length?rows.map(([code,title,icon])=>`<button class="module-link ${state.page===code?'active':''}" onclick="setPage('${code}')"><span class="module-symbol" data-copy-icon="${icon}"></span>${title}<span class="module-count">${moduleCount(code)}</span></button>`).join('')+`<span class="hidden" id="ribbonTasksCount">0</span>`:`<div class="module-placeholder"><span data-copy-icon="settings"></span><span>Панель быстрого доступа пуста — выберите нужные разделы в Настройках.</span></div><span class="hidden" id="ribbonTasksCount">0</span>`;host.querySelectorAll('[data-copy-icon]').forEach(el=>copyIcon(el,el.dataset.copyIcon))}
  const canCompanyModule=code=>{const r=state.profile?.role;if(['owner','admin'].includes(r))return true;const map={accountant:['estimates','financial_accounting','procurement','warehouse_accounting'],project_manager:['estimates','work_schedule','financial_accounting','procurement','site_control','warehouse_accounting'],foreman:['work_schedule','procurement','site_control','warehouse_accounting'],designer:['estimates','work_schedule'],procurement:['estimates','work_schedule','procurement','warehouse_accounting'],storekeeper:['procurement','warehouse_accounting'],employee:['site_control']};return (map[r]||[]).includes(code)};
  updateShell=function(){baseUpdate();['estimates','work_schedule','financial_accounting','procurement','site_control','warehouse_accounting'].forEach(code=>{const b=document.querySelector(`.nav-btn[data-page="${code}"]`);if(b)b.classList.toggle('hidden',!canCompanyModule(code))});renderRibbon()};
  function navigationSettings(){const selected=pinned();return `<section class="panel"><div class="panel-head"><div><h2>Горизонтальная панель быстрого доступа</h2><p>Все разделы постоянно находятся слева. Здесь можно выборочно закрепить нужные кнопки наверху.</p></div><button class="btn primary" onclick="saveNavigationPins()">Сохранить панель</button></div><div class="pin-grid">${MODULES.map(([code,title,icon])=>`<label class="pin-choice"><input type="checkbox" name="navigation_pin" value="${code}" ${selected.includes(code)?'checked':''}><span class="nav-icon" data-icon="${icon}"></span><span><b>${title}</b><small>${selected.includes(code)?'Сейчас закреплён наверху':'Только в левом меню'}</small></span></label>`).join('')}</div><div style="padding:0 16px 16px" class="muted">Если ничего не отмечать, наверху останется свободное место с подсказкой.</div></section>`}
  settingsPage=function(){return navigationSettings()+`<div class="section-gap">${baseSettings()}</div>`};
  window.saveNavigationPins=async()=>{const modules=[...document.querySelectorAll('input[name="navigation_pin"]:checked')].map(x=>x.value),current=navSetting(),record={setting_key:'navigation_pins',setting_value:{modules}};if(current){const updated=await update('app_settings',current.id,record);state.settings[state.settings.findIndex(x=>x.id===current.id)]=updated}else state.settings.push(await insert('app_settings',record));renderPage();toast('Панель быстрого доступа сохранена в облаке')};

  const dayDivisor=()=>Number(state.payrollSettings?.[0]?.salary_day_divisor||30),hoursPerDay=()=>Number(state.payrollSettings?.[0]?.hours_per_day||10);
  const monthName=m=>new Intl.DateTimeFormat('ru',{month:'long'}).format(new Date(2026,m-1,1));
  const isoDay=(y,m,d)=>`${y}-${String(m).padStart(2,'0')}-${String(d).padStart(2,'0')}`;
  const periodEvents=(year=state.payrollYear,month=state.payrollMonth)=>state.attendanceEvents.filter(x=>{const d=new Date(x.event_date+'T00:00:00');return d.getFullYear()===Number(year)&&d.getMonth()+1===Number(month)});
  const rateInfo=e=>{const monthly=Number(e.monthly_salary||0),isMonthly=e.payment_type==='monthly',daily=isMonthly?monthly/dayDivisor():(Number(e.daily_rate||0)||monthly/dayDivisor()),hourly=isMonthly?daily/hoursPerDay():(Number(e.hourly_rate||0)||daily/hoursPerDay()),overtime=isMonthly?hourly:(Number(e.overtime_rate||0)||hourly);return {monthly,daily,hourly,overtime}};
  const employeeCalc=(e,year=state.payrollYear,month=state.payrollMonth)=>{const ev=periodEvents(year,month).filter(x=>x.employee_id===e.id),r=rateInfo(e),ot=ev.filter(x=>x.event_type==='overtime'),abs=ev.filter(x=>x.event_type==='absence'),adv=ev.filter(x=>x.event_type==='advance'),otHours=ot.reduce((a,x)=>a+Number(x.quantity||0),0),absHours=abs.reduce((a,x)=>a+Number(x.quantity||0),0),otPay=ot.reduce((a,x)=>a+Number(x.amount||0),0),absAmount=abs.reduce((a,x)=>a+Number(x.amount||0),0),advance=adv.reduce((a,x)=>a+Number(x.amount||0),0),base=e.payment_type==='monthly'?r.monthly:Number(state.payrollEntries.find(x=>x.employee_id===e.id&&state.payrollPeriods.find(p=>p.id===x.payroll_period_id&&Number(p.period_year)===Number(year)&&Number(p.period_month)===Number(month)))?.base_amount||0),earned=base+otPay+absAmount;return {base,otHours,absHours,otPay,absAmount,earned,advance,toPay:earned-advance,r}};
  const fmt=n=>money(Number(n||0)),neg=n=>Number(n)<0?`<span class="salary-negative">(${fmt(Math.abs(n))})</span>`:fmt(n),eventLabel=t=>({overtime:'Overtime',absence:'Absence',advance:'Advance'}[t]||t);
  const table=(heads,rows,cls='')=>`<div class="table-wrap"><table class="data-table ${cls}"><thead><tr>${heads.map(x=>`<th>${x}</th>`).join('')}</tr></thead><tbody>${rows.map(r=>`<tr>${r.map(x=>`<td>${x??'—'}</td>`).join('')}</tr>`).join('')||`<tr><td colspan="${heads.length}" class="empty">Нет данных</td></tr>`}</tbody></table></div>`;
  function workersTab(){const total=state.employees.reduce((a,e)=>a+rateInfo(e).monthly,0);return `<section class="panel"><div class="salary-sheet-head"><h2>SPACE BURO — СОТРУДНИКИ И СТАВКИ</h2><p>Дневная ставка = месячная ÷ ${dayDivisor()} · почасовая = дневная ÷ ${hoursPerDay()}</p></div>${table(['#','СОТРУДНИК','ЗАРПЛАТА / МЕСЯЦ','ЗАРПЛАТА / ДЕНЬ','ЗА ЧАС','OVERTIME','ТИП ОПЛАТЫ',''],state.employees.map((e,i)=>{const r=rateInfo(e);return [i+1,`<b>${esc(e.full_name)}</b><br><small>${esc(e.job_title||'Сотрудник')}</small>`,fmt(r.monthly)+' AED',fmt(r.daily)+' AED',r.hourly.toFixed(2)+' AED',r.overtime.toFixed(2)+' AED',esc(e.payment_type),`<button class="btn" onclick="editRecord('employee','${e.id}')">Изменить</button>`]}),'salary-table')}<div class="finance-summary"><div class="summary-line"><span>Общий месячный фонд</span><b>${fmt(total)} AED</b></div><div class="summary-line"><span>Правило присутствия</span><b>Все присутствуют по умолчанию</b></div></div></section>`}
  function journalTab(){const events=periodEvents().slice().sort((a,b)=>String(a.event_date).localeCompare(String(b.event_date)));return `<section class="panel"><div class="salary-sheet-head"><h2>SPACE BURO — ЖУРНАЛ</h2><p>Записываются только Absence / Overtime / Advance</p></div><div class="toolbar"><button class="btn primary" onclick="openAttendanceEventExact()">＋ Запись</button><span class="tag event-overtime">Overtime · часы</span><span class="tag event-absence">Absence · часы</span><span class="tag event-advance">Advance · AED</span></div>${table(['ДАТА','ДЕНЬ','СОТРУДНИК','ТИП','КОЛ-ВО','СУММА','МЕСЯЦ','ПРИМЕЧАНИЕ',''],events.map(x=>{const d=new Date(x.event_date+'T00:00:00'),tone=x.event_type==='advance'?'salary-advance':x.event_type==='absence'?'salary-negative':'salary-positive';return [date(x.event_date),new Intl.DateTimeFormat('ru',{weekday:'short'}).format(d),esc(state.employees.find(e=>e.id===x.employee_id)?.full_name||'—'),`<span class="${tone}">${eventLabel(x.event_type)}</span>`,Number(x.quantity||0),`<span class="${tone}">${x.event_type==='absence'?neg(x.amount):fmt(x.amount)}</span>`,monthName(d.getMonth()+1),esc(x.notes||'—'),`<button class="btn" onclick="openAttendanceEventExact('${x.id}')">Изменить</button> <button class="btn danger" onclick="deleteAttendanceEvent('${x.id}')">×</button>`]}),'salary-table')}</section>`}
  function summaryTab(){const rows=state.employees.map(e=>[e,employeeCalc(e)]),tot=k=>rows.reduce((a,x)=>a+Number(x[1][k]||0),0);return `<div class="kpis">${kpi('AED','Базовая зарплата',fmt(tot('base')),'AED')}${kpi('↑','Заработано',fmt(tot('earned')),'AED')}${kpi('↓','Авансы',fmt(tot('advance')),'AED')}${kpi('◷','К выплате',fmt(tot('toPay')),'AED')}</div><section class="panel"><div class="salary-sheet-head"><h2>SPACE BURO — СВОДКА ${state.payrollYear} · ${monthName(state.payrollMonth).toUpperCase()}</h2><p>EARNED = salary − absence + overtime · TO PAY = earned − advance</p></div><div class="table-wrap"><table class="data-table salary-table"><thead><tr><th>СОТРУДНИК</th><th>BASE SALARY</th><th>OT h</th><th>ABS h</th><th>OT PAY</th><th>ABS −</th><th>EARNED</th><th>ADVANCE</th><th>TO PAY</th></tr></thead><tbody>${rows.map(([e,x])=>`<tr><td><b>${esc(e.full_name)}</b></td><td>${fmt(x.base)}</td><td>${x.otHours||'—'}</td><td class="salary-negative">${x.absHours||'—'}</td><td>${fmt(x.otPay)}</td><td>${neg(x.absAmount)}</td><td class="salary-earned">${fmt(x.earned)}</td><td class="salary-advance">${fmt(x.advance)}</td><td class="salary-pay">${fmt(x.toPay)}</td></tr>`).join('')}</tbody><tfoot><tr><td>ИТОГО</td><td>${fmt(tot('base'))}</td><td>${tot('otHours')}</td><td>${tot('absHours')}</td><td>${fmt(tot('otPay'))}</td><td>${neg(tot('absAmount'))}</td><td>${fmt(tot('earned'))}</td><td>${fmt(tot('advance'))}</td><td>${fmt(tot('toPay'))}</td></tr></tfoot></table></div></section>`}
  function yearTab(){const months=Array.from({length:12},(_,i)=>i+1);return `<section class="panel"><div class="salary-sheet-head"><h2>SPACE BURO — ГОДОВАЯ СВОДКА ${state.payrollYear}</h2><p>TO PAY по каждому сотруднику и месяцу</p></div><div class="table-wrap"><table class="data-table salary-table year-summary"><thead><tr><th>СОТРУДНИК</th>${months.map(m=>`<th>${monthName(m).slice(0,3).toUpperCase()}</th>`).join('')}<th>ИТОГО</th></tr></thead><tbody>${state.employees.map(e=>{const values=months.map(m=>employeeCalc(e,state.payrollYear,m).toPay);return `<tr><td><b>${esc(e.full_name)}</b></td>${values.map(v=>`<td>${fmt(v)}</td>`).join('')}<td class="salary-pay">${fmt(values.reduce((a,x)=>a+x,0))}</td></tr>`}).join('')}</tbody><tfoot><tr><td>ИТОГО</td>${months.map(m=>`<td>${fmt(state.employees.reduce((a,e)=>a+employeeCalc(e,state.payrollYear,m).toPay,0))}</td>`).join('')}<td>${fmt(months.reduce((a,m)=>a+state.employees.reduce((s,e)=>s+employeeCalc(e,state.payrollYear,m).toPay,0),0))}</td></tr></tfoot></table></div></section>`}
  function calendarTab(){const days=new Date(state.payrollYear,state.payrollMonth,0).getDate(),events=periodEvents(),heads=['ДЕНЬ','ТИП',...state.employees.map(e=>esc(e.full_name)),'TOTAL'];let rows='';for(let d=1;d<=days;d++){for(const type of ['overtime','absence']){const vals=state.employees.map(e=>events.filter(x=>x.employee_id===e.id&&x.event_type===type&&Number(String(x.event_date).slice(8,10))===d).reduce((a,x)=>a+Number(x.quantity||0),0)),total=vals.reduce((a,x)=>a+x,0);rows+=`<tr class="${type==='overtime'?'ot-row':'abs-row'}"><td class="salary-day">${type==='overtime'?d:''}</td><td class="salary-kind">${type==='overtime'?'Overtime +h':'Absence −h'}</td>${vals.map((v,i)=>`<td class="clickable-cell" onclick="openAttendanceForCell('${state.employees[i].id}','${isoDay(state.payrollYear,state.payrollMonth,d)}','${type}')">${v||'·'}</td>`).join('')}<td><b>${total||0}</b></td></tr>`}}return `<section class="panel"><div class="salary-sheet-head"><h2>SPACE BURO — КАЛЕНДАРЬ ${monthName(state.payrollMonth).toUpperCase()} ${state.payrollYear}</h2><p>Две строки на день: overtime (зелёный +h) / absence (красный −h). Нажмите ячейку, чтобы добавить запись.</p></div><div class="table-wrap"><table class="data-table salary-table salary-calendar"><thead><tr>${heads.map(x=>`<th>${x}</th>`).join('')}</tr></thead><tbody>${rows}</tbody></table></div></section>`}
  function adjustmentsTab(){const rows=state.payrollAdjustments.filter(a=>Number(a.period_year||new Date(a.adjustment_date).getFullYear())===state.payrollYear&&Number(a.period_month||new Date(a.adjustment_date).getMonth()+1)===state.payrollMonth);return `<section class="panel"><div class="salary-sheet-head"><h2>ДОПОЛНИТЕЛЬНЫЕ НАЧИСЛЕНИЯ И ВЫПЛАТЫ</h2><p>Бонусы, штрафы, оплата за проект, выплата зарплаты и другие корректировки</p></div><div class="toolbar"><button class="btn primary" onclick="openPayrollAdjustment()">＋ Операция</button></div>${table(['ДАТА','СОТРУДНИК','ТИП','ПРОЕКТ','СПОСОБ','КОММЕНТАРИЙ','СУММА'],rows.map(a=>[date(a.adjustment_date),esc(state.employees.find(e=>e.id===a.employee_id)?.full_name||'—'),esc(a.adjustment_type),esc(state.projects.find(p=>p.id===a.project_id)?.name||'—'),esc(a.payment_method||'—'),esc(a.notes||'—'),`<b>${fmt(a.amount)} AED</b>`]),'salary-table')}</section>`}
  function designTab(){return `<section class="panel"><div class="salary-sheet-head"><h2>ЧЕРТЁЖНИКИ ПО ПРОЕКТАМ</h2><p>SketchUp / Revit / Базис-Мебельщик · этапы · правки · ошибки · материал-бонус</p></div><div class="toolbar"><button class="btn primary" onclick="openDesignCompensation()">＋ Проектный расчёт</button></div>${table(['ПРОЕКТ','ПОМЕЩЕНИЕ','ЧЕРТЁЖНИК','МАТЕРИАЛЫ','БОНУС','ПРОГРАММЫ','К ВЫПЛАТЕ'],state.designCompensations.map(c=>[`<button class="btn" onclick="openDesignCompensation('${c.id}')">${esc(c.project_number||state.projects.find(p=>p.id===c.project_id)?.name||'Проект')}</button>`,esc(c.room_type||'—'),esc(c.designer_name||state.employees.find(e=>e.id===c.designer_id)?.full_name||'—'),fmt(c.material_total),fmt(c.material_bonus),fmt(c.program_total),`<b>${fmt(c.final_payment)} AED</b>`]),'salary-table')}</section>`}
  payrollPage=function(){const tabs=[['workers','Сотрудники и ставки'],['journal','Журнал'],['summary','Сводка месяца'],['year','Сводка года'],['calendar','Календарь'],['adjustments','Начисления и выплаты'],['design','Чертёжники']];const body={workers:workersTab,journal:journalTab,summary:summaryTab,year:yearTab,calendar:calendarTab,adjustments:adjustmentsTab,design:designTab}[state.payrollTab]||summaryTab;return `<div class="toolbar panel"><select class="field" onchange="setPayrollMonth(this.value)">${Array.from({length:12},(_,i)=>`<option value="${i+1}" ${state.payrollMonth===i+1?'selected':''}>${monthName(i+1)}</option>`).join('')}</select><select class="field" onchange="setPayrollYear(this.value)">${[state.payrollYear-1,state.payrollYear,state.payrollYear+1].map(y=>`<option ${state.payrollYear===y?'selected':''}>${y}</option>`).join('')}</select><button class="btn" onclick="calculatePayroll()">Пересчитать</button><div class="payroll-tabs">${tabs.map(([v,n])=>`<button class="btn ${state.payrollTab===v?'primary':''}" onclick="setPayrollTab('${v}')">${n}</button>`).join('')}</div></div><div class="section-gap">${body()}</div>`};
  window.openAttendanceEventExact=id=>{const x=state.attendanceEvents.find(e=>e.id===id)||{},selected=x.event_date||isoDay(state.payrollYear,state.payrollMonth,1);openModal(id?'Изменить запись журнала':'Новая запись журнала',input('event_date','Дата','date',selected,'required')+select('employee_id','Сотрудник','<option value="">Выберите</option>'+state.employees.map(e=>`<option value="${e.id}" ${e.id===x.employee_id?'selected':''}>${esc(e.full_name)}</option>`).join(''))+select('event_type','Тип',`<option value="absence" ${x.event_type==='absence'?'selected':''}>Absence · часы</option><option value="overtime" ${x.event_type==='overtime'?'selected':''}>Overtime · часы</option><option value="advance" ${x.event_type==='advance'?'selected':''}>Advance · AED</option>`)+input('quantity','Количество часов или сумма','number',x.quantity||0,'required step="0.01" min="0"')+select('project_id','Проект','<option value="">Без проекта</option>'+state.projects.map(p=>`<option value="${p.id}" ${p.id===x.project_id?'selected':''}>${esc(p.name)}</option>`).join(''))+`<label class="full">Примечание<textarea name="notes">${esc(x.notes||'')}</textarea></label>`,async d=>{if(!d.employee_id)throw new Error('Выберите сотрудника');const rec={event_date:d.event_date,employee_id:d.employee_id,event_type:d.event_type,quantity:Number(d.quantity||0),project_id:d.project_id||null,notes:d.notes||null};return id?update('payroll_attendance_events',id,rec):insert('payroll_attendance_events',rec)})};
  window.openAttendanceForCell=(employee,dateValue,type)=>{openAttendanceEventExact();setTimeout(()=>{const f=$('#modalForm');if(!f)return;f.elements.employee_id.value=employee;f.elements.event_date.value=dateValue;f.elements.event_type.value=type},0)};
  window.deleteAttendanceEvent=async id=>{if(!confirm('Удалить эту запись журнала?'))return;await rawApi(`/rest/v1/payroll_attendance_events?id=eq.${id}`,{method:'DELETE'});await loadAll();toast('Запись удалена')};
  window.setPayrollTab=t=>{state.payrollTab=t;renderPage()};
  renderPage=function(){baseRender();renderRibbon()};
  actionForPage=function(){if(state.page==='payroll'){if(['journal','calendar'].includes(state.payrollTab))return openAttendanceEventExact();if(state.payrollTab==='design')return openDesignCompensation();if(state.payrollTab==='workers')return openEmployeeModal();return openPayrollAdjustment()}return baseAction()};
  $('#pageAction').onclick=actionForPage;
  $$('.nav-btn').forEach(b=>b.onclick=()=>setPage(b.dataset.page));
  updateShell();renderPage();
})();
