(function(){
  const baseRender17=renderPage,baseAction17=actionForPage;
  Object.assign(state,{estimateHubTab:state.estimateHubTab||'estimates'});
  const n17=v=>Number(v||0),sum17=(rows,fn)=>rows.reduce((a,x)=>a+n17(fn(x)),0);
  const records17=code=>(state.moduleRecords||[]).filter(x=>x.module_code===code&&!x.deleted_at&&!x.archived_at);
  const estimateLines17=id=>(state.moduleLines||[]).filter(x=>x.record_id===id).sort((a,b)=>n17(a.sort_order)-n17(b.sort_order)||String(a.created_at).localeCompare(String(b.created_at)));
  const catalog17=()=>records17('rate_catalog').filter(x=>['work_category','work_type','subwork'].includes(x.record_type));
  const catalogChildren17=id=>catalog17().filter(x=>x.parent_id===id);
  const catalogMaterials17=id=>(state.moduleLines||[]).filter(x=>x.record_id===id&&x.line_type==='material');
  const project17=id=>state.projects.find(x=>x.id===id)?.name||'—',client17=id=>state.clients.find(x=>x.id===id)?.name||'—';
  const local17=v=>typeof v==='object'&&v?(v.en||v.ru||Object.values(v)[0]||'—'):(v||'—');
  const opts17=(rows,value='id',label='name',selected='')=>rows.map(x=>`<option value="${esc(x[value])}" ${String(x[value])===String(selected)?'selected':''}>${esc(local17(x[label]))}</option>`).join('');
  const table17=(heads,rows,cls='')=>`<div class="table-wrap"><table class="data-table ${cls}"><thead><tr>${heads.map(x=>`<th>${x}</th>`).join('')}</tr></thead><tbody>${rows.map(r=>`<tr ${r.attr||''}>${r.cells.map(x=>`<td>${x??'—'}</td>`).join('')}</tr>`).join('')||`<tr><td colspan="${heads.length}" class="empty">Нет данных</td></tr>`}</tbody></table></div>`;
  const status17=s=>`<span class="status ${statusTone(s)}">${esc(String(s||'draft').replaceAll('_',' '))}</span>`;
  const unitOptions17=selected=>[['pcs','Pieces'],['m','Metre'],['m2','Square metre'],['m3','Cubic metre'],['lm','Linear metre'],['kg','Kilogram'],['ton','Tonne'],['set','Set'],['lot','Lot'],['hour','Hour'],['day','Day']].map(([v,t])=>`<option value="${v}" ${v===selected?'selected':''}>${t} (${v})</option>`).join('');
  const stockAvailable17=id=>(state.stock||[]).filter(x=>x.material_id===id).reduce((a,x)=>a+n17(x.quantity_on_hand)-n17(x.reserved),0);
  const materialOptions17=selected=>`<option value="">Select material</option>`+state.materials.map(m=>`<option value="${m.id}" ${m.id===selected?'selected':''}>${esc(m.name)} · cost ${money(m.purchase_price)} · sale ${money(m.sale_price)} AED · available ${stockAvailable17(m.id)} ${esc(m.unit)}</option>`).join('');
  const lineKind17=x=>x.line_type==='section'?'Раздел':x.line_type==='work'?'Вид работ':x.line_type==='subwork'?'Подработа':x.line_type==='material'?'Материал':x.line_type;
  const lineSymbol17=x=>x.line_type==='section'?'§':x.line_type==='work'?'W':x.line_type==='subwork'?'↳':x.line_type==='material'?'M':'•';
  const estimateTotal17=ls=>({cost:sum17(ls,x=>n17(x.quantity)*n17(x.unit_cost)),sale:sum17(ls,x=>n17(x.quantity)*n17(x.unit_sale))});
  const nextNumber17=prefix=>`${prefix}-${new Date().getFullYear()}-${String(Date.now()).slice(-6)}`;

  function lineDepth17(line,map){let d=0,p=line.parent_line_id,guard=0;while(p&&map.has(p)&&guard++<8){d++;p=map.get(p).parent_line_id}return d}
  function descendants17(id,ls){const result=new Set(),walk=p=>ls.filter(x=>x.parent_line_id===p).forEach(x=>{result.add(x.id);walk(x.id)});walk(id);return result}
  async function recalcEstimate17(id){const fresh=await rawApi(`/rest/v1/module_record_lines?select=*&record_id=eq.${id}`),tot=estimateTotal17(fresh);await update('module_records',id,{cost_amount:tot.cost,sale_amount:tot.sale,planned_amount:tot.sale});return tot}
  async function reload17(){await loadAll()}

  function estimateList17(){const rs=records17('estimates'),sale=sum17(rs,x=>x.sale_amount),cost=sum17(rs,x=>x.cost_amount);return `<div class="module-summary">${kpi('▤','Смет',rs.length,'все проекты')}${kpi('✓','Утверждено',rs.filter(x=>['agreed','approved'].includes(x.status)).length,'готовы к задачам')}${kpi('AED','Цена продажи',money(sale),'AED')}${kpi('%','Плановая маржа',sale?Math.round((sale-cost)/sale*100):0,'%')}</div><section class="panel section-gap">${table17(['СМЕТА','КЛИЕНТ / ПРОЕКТ','СТАТУС','РАЗДЕЛЫ','РАБОТЫ','МАТЕРИАЛЫ','СЕБЕСТОИМОСТЬ','ПРОДАЖА','СВЯЗЬ'],rs.map(r=>{const ls=estimateLines17(r.id);return {cells:[`<button class="btn" onclick="openEstimate17('${r.id}')">${esc(r.record_number||'EST')}</button><br><small>${esc(r.name)}</small>`,`${esc(client17(r.client_id))}<br><small>${esc(project17(r.project_id))}</small>`,status17(r.status),ls.filter(x=>x.line_type==='section').length,ls.filter(x=>['work','subwork'].includes(x.line_type)).length,ls.filter(x=>x.line_type==='material').length,money(r.cost_amount)+' AED',money(r.sale_amount)+' AED',r.data?.schedule_id?'<span class="status green">Tasks + schedule</span>':'<span class="status gray">Not generated</span>']}}))}</section>`}
  function estimateHub17(){return `<div class="module-hero"><div><h2>Сметы и BOQ — конструктор работ</h2><p>Создайте библиотеку работ один раз, привяжите подработы и материалы, затем собирайте смету готовыми пакетами.</p></div><div class="action-row"><button class="btn" onclick="setEstimateHubTab17('library')">Библиотека работ</button><button class="btn primary" onclick="openEstimateCreate16()">＋ Новая смета</button></div></div><div class="panel estimate-flow"><span>1. Проект</span><i>→</i><span>2. Смета / BOQ</span><i>→</i><span>3. Виды работ и подработы</span><i>→</i><span>4. Задачи</span><i>→</i><span>5. График и контроль</span><i>→</i><span>6. Материалы и финансы</span></div><div class="module-tabs section-gap"><button class="btn ${state.estimateHubTab==='estimates'?'primary':''}" onclick="setEstimateHubTab17('estimates')">Сметы</button><button class="btn ${state.estimateHubTab==='library'?'primary':''}" onclick="setEstimateHubTab17('library')">Библиотека видов работ</button></div>${state.estimateHubTab==='library'?workLibrary17():estimateList17()}`}
  window.setEstimateHubTab17=t=>{state.estimateHubTab=t;renderPage()};

  function workLibrary17(){const cats=catalog17().filter(x=>x.record_type==='work_category'),packages=catalog17().filter(x=>['work_type','subwork'].includes(x.record_type));return `<div class="toolbar panel"><button class="btn primary" onclick="openWorkCatalog17('work_category')">＋ Категория</button><button class="btn" onclick="openWorkCatalog17('work_type')">＋ Вид работ</button><button class="btn" onclick="openWorkCatalog17('subwork')">＋ Подработа</button><button class="btn" onclick="setPage('warehouse_accounting')">Материалы и цены →</button></div><div class="work-library-grid section-gap"><section class="panel"><div class="panel-head"><div><h2>Структура работ</h2><p>Категория → вид работ → подработа</p></div></div><div class="work-tree">${cats.map(c=>workTreeCategory17(c)).join('')||'<div class="estimate-empty-guide"><b>Начните с категории</b><p>Например: Demolition, Electrical, Plumbing, Tiling, Painting, Joinery.</p></div>'}</div></section><section class="panel"><div class="panel-head"><div><h2>Пакеты работ и материалы</h2><p>Цена работы плюс автоматический список материалов на единицу объёма</p></div></div>${packages.map(p=>workPackageCard17(p)).join('')||'<div class="estimate-empty-guide"><b>Пакетов работ пока нет</b><p>Добавьте вид работ, затем подработы и материалы с нормами расхода.</p></div>'}</section></div>`}
  function workTreeCategory17(c){const works=catalogChildren17(c.id).filter(x=>x.record_type==='work_type');return `<div class="work-tree-node"><div class="work-tree-head"><div><b>${esc(c.name)}</b><small>${works.length} видов работ</small></div><button class="btn" onclick="openWorkCatalog17('work_type','','${c.id}')">＋ Work</button><button class="btn" onclick="editWorkCatalog17('${c.id}')">Edit</button></div><div class="work-children">${works.map(w=>`<div class="work-tree-head"><div><b>${esc(w.name)}</b><small>${catalogChildren17(w.id).filter(x=>x.record_type==='subwork').length} подработ · ${esc(w.data?.unit||'unit')}</small></div><button class="btn" onclick="openWorkCatalog17('subwork','','${w.id}')">＋ Subwork</button></div>`).join('')||'<span class="muted">Виды работ не добавлены</span>'}</div></div>`}
  function workPackageCard17(p){const parent=catalog17().find(x=>x.id===p.parent_id),ms=catalogMaterials17(p.id);return `<article class="work-package"><div class="work-package-top"><div><h3>${p.record_type==='subwork'?'↳ ':''}${esc(p.name)}</h3><p>${esc(parent?.name||'Без категории')} · ${esc(p.data?.description||'')}</p><div class="price-pills"><span>${esc(p.data?.unit||'unit')}</span><span>Cost ${money(p.cost_amount)} AED</span><span>Sale ${money(p.sale_amount)} AED</span><span>${n17(p.data?.default_duration_days)} days</span></div></div><button class="btn" onclick="openWorkMaterial17('${p.id}')">＋ Material</button><button class="btn" onclick="editWorkCatalog17('${p.id}')">Edit</button></div><div class="material-components">${ms.map(x=>{const m=state.materials.find(y=>y.id===x.material_id);return `<div class="material-component"><span>${esc(m?.name||x.name)} · ${n17(x.quantity)} ${esc(x.unit)} / ${esc(p.data?.unit||'unit')}</span><span><b>${money(x.unit_sale)} AED</b> <button class="btn" onclick="openWorkMaterial17('${p.id}','${x.id}')">Edit</button></span></div>`}).join('')||'<span class="muted">Материалы не привязаны</span>'}</div></article>`}

  window.openWorkCatalog17=(type,id='',parentPreset='')=>{const row=id?state.moduleRecords.find(x=>x.id===id):{},categories=catalog17().filter(x=>x.record_type==='work_category'),works=catalog17().filter(x=>x.record_type==='work_type'),parents=type==='work_type'?categories:type==='subwork'?works:[],title={work_category:'Категория работ',work_type:'Вид работ',subwork:'Подработа'}[type];openModal(id?'Изменить '+title:'Новая '+title,(type==='work_category'?'':select('parent_id','Parent',`<option value="">Select parent</option>`+opts17(parents,'id','name',row.parent_id||parentPreset)))+input('name','Name','text',row.name||'','required')+input('code','Code','text',row.record_number||'')+(type==='work_category'?'':select('unit','Unit',unitOptions17(row.data?.unit||'m2'))+input('cost_amount','Labour / work cost · AED','number',row.cost_amount||0,'step="0.01"')+input('sale_amount','Work sale price · AED','number',row.sale_amount||0,'step="0.01"')+input('default_duration_days','Default duration · days','number',row.data?.default_duration_days||1,'min="0" step="0.5"'))+`<label class="full">Description<textarea name="description">${esc(row.data?.description||'')}</textarea></label>`,async d=>{const rec={module_code:'rate_catalog',record_type:type,record_number:d.code||nextNumber17(type==='work_category'?'CAT':type==='work_type'?'WORK':'SUB'),name:d.name,parent_id:d.parent_id||null,status:'active',currency:'AED',cost_amount:n17(d.cost_amount),sale_amount:n17(d.sale_amount),data:{...(row.data||{}),unit:d.unit||'item',description:d.description||'',default_duration_days:n17(d.default_duration_days),task_required:type!=='work_category'}};id?await update('module_records',id,rec):await insert('module_records',rec);await reload17()})};
  window.editWorkCatalog17=id=>{const r=state.moduleRecords.find(x=>x.id===id);openWorkCatalog17(r.record_type,id)};
  window.openWorkMaterial17=(catalogId,lineId='')=>{const x=lineId?state.moduleLines.find(y=>y.id===lineId):{};openModal(lineId?'Изменить материал работы':'Материал для работы',select('material_id','Material',materialOptions17(x.material_id))+input('quantity','Consumption per work unit','number',x.quantity||1,'step="0.001" min="0"')+select('unit','Unit',unitOptions17(x.unit||'pcs'))+input('waste_percent','Waste · %','number',x.data?.waste_percent||0,'step="0.01" min="0"')+input('unit_cost','Unit cost · AED','number',x.unit_cost||0,'step="0.01"')+input('unit_sale','Unit sale · AED','number',x.unit_sale||0,'step="0.01"')+`<label class="full">Comment<textarea name="description">${esc(x.description||'')}</textarea></label>`,async d=>{if(!d.material_id)throw new Error('Select material');const m=state.materials.find(z=>z.id===d.material_id),rec={record_id:catalogId,line_type:'material',name:m?.name||'Material',description:d.description||null,material_id:d.material_id,quantity:n17(d.quantity),unit:d.unit||m?.unit||'pcs',unit_cost:n17(d.unit_cost),unit_sale:n17(d.unit_sale),status:'active',sort_order:catalogMaterials17(catalogId).length+1,data:{waste_percent:n17(d.waste_percent),component:true}};lineId?await update('module_record_lines',lineId,rec):await insert('module_record_lines',rec);await reload17()});setTimeout(()=>bindMaterialFill17(),0)};

  function bindMaterialFill17(){const f=$('#modalForm'),sel=f?.elements.material_id;if(!sel)return;const fill=force=>{const m=state.materials.find(x=>x.id===sel.value);if(!m)return;if(f.elements.name&&(force||!f.elements.name.value))f.elements.name.value=m.name;if(f.elements.unit)f.elements.unit.value=m.unit||'pcs';if(f.elements.unit_cost&&(force||!n17(f.elements.unit_cost.value)))f.elements.unit_cost.value=n17(m.purchase_price);if(f.elements.unit_sale&&(force||!n17(f.elements.unit_sale.value)))f.elements.unit_sale.value=n17(m.sale_price||m.purchase_price)};sel.onchange=()=>fill(true);if(sel.value)fill(false)}

  window.openEstimate17=id=>{const r=state.moduleRecords.find(x=>x.id===id);if(!r)return;const ls=estimateLines17(id),map=new Map(ls.map(x=>[x.id,x])),tot=estimateTotal17(ls),profit=tot.sale-tot.cost,rows=ls.map(x=>{const depth=lineDepth17(x,map),mat=state.materials.find(m=>m.id===x.material_id);return {attr:`data-kind="${x.line_type}"`,cells:[`<div class="boq-name"><span class="boq-indent" style="width:${depth*22}px"></span><span class="boq-type">${lineSymbol17(x)}</span><div><b>${esc(x.name)}</b><br><small>${esc(mat?mat.name:x.description||lineKind17(x))}</small></div></div>`,esc(lineKind17(x)),n17(x.quantity),esc(x.unit),money(x.unit_cost),money(x.unit_sale),money(n17(x.quantity)*n17(x.unit_sale)),x.linked_task_id?'<span class="status green">Task linked</span>':'—',`<div class="boq-actions"><button class="btn" onclick="editEstimateLine17('${id}','${x.id}')">Edit</button><button class="btn danger" onclick="deleteEstimateLine17('${id}','${x.id}')">×</button></div>`]}});$('#drawerNumber').textContent=r.record_number||'ESTIMATE';$('#drawerContent').innerHTML=`<h2 class="drawer-title">${esc(r.name)}</h2><p class="drawer-sub">${esc(client17(r.client_id))} · ${esc(project17(r.project_id))}</p><div class="detail-grid"><div class="detail-box"><span>Cost</span><b>${money(tot.cost)} AED</b></div><div class="detail-box"><span>Sale</span><b>${money(tot.sale)} AED</b></div><div class="detail-box"><span>Profit</span><b>${money(profit)} AED</b></div><div class="detail-box"><span>Margin</span><b>${tot.sale?Math.round(profit/tot.sale*100):0}%</b></div></div><div class="action-row"><button class="btn" onclick="addEstimateSection17('${id}')">＋ Раздел</button><button class="btn primary" onclick="addWorkPackage17('${id}')">＋ Вид работ из библиотеки</button><button class="btn" onclick="addManualEstimateLine17('${id}')">＋ Ручная строка</button><button class="btn" onclick="approveEstimate16('${id}')">Approve & version</button><button class="btn primary" onclick="syncEstimateExecution17('${id}')" ${!['agreed','approved'].includes(r.status)?'disabled':''}>Создать / обновить задачи и график</button><button class="btn" onclick="estimatePdf16('${id}',false)">Client PDF</button></div><section class="panel section-gap">${ls.length?table17(['ПОЗИЦИЯ','ТИП','КОЛ-ВО','ЕД.','COST','SALE','TOTAL','ЗАДАЧА',''],rows,'boq-tree'):`<div class="estimate-empty-guide"><b>Смета пока пустая</b><p>Добавьте раздел, затем выберите готовый вид работ. Подработы и материалы с ценами добавятся автоматически.</p><button class="btn primary" onclick="addEstimateSection17('${id}')">Начать с раздела</button></div>`}</section>`;$('#drawerOverlay').classList.add('show');document.body.classList.add('overlay-lock')};
  window.openEstimate16=window.openEstimate17;

  window.addEstimateSection17=id=>openModal('Новый раздел сметы',select('parent_line_id','Parent section',`<option value="">Top level</option>`+opts17(estimateLines17(id).filter(x=>x.line_type==='section'),'id','name'))+input('code','Code')+input('name','Section name','text','','required'),async d=>{await insert('module_record_lines',{record_id:id,parent_line_id:d.parent_line_id||null,line_type:'section',code:d.code||null,name:d.name,quantity:0,unit:'section',unit_cost:0,unit_sale:0,status:'draft',sort_order:estimateLines17(id).length+1,data:{builder:'phase1_7'}});await recalcEstimate17(id);await reload17()});
  window.addWorkPackage17=id=>{const packages=catalog17().filter(x=>['work_type','subwork'].includes(x.record_type)),parents=estimateLines17(id).filter(x=>['section','work','subwork'].includes(x.line_type));openModal('Добавить вид работ из библиотеки',select('catalog_id','Work / subwork',`<option value="">Select work</option>`+packages.map(x=>`<option value="${x.id}">${x.record_type==='subwork'?'↳ ':''}${esc(x.name)} · ${esc(x.data?.unit||'unit')} · ${money(x.sale_amount)} AED</option>`).join(''))+select('parent_line_id','Estimate section / parent work',`<option value="">Top level</option>`+opts17(parents,'id','name'))+input('quantity','Work quantity','number','1','step="0.001" min="0.001"')+select('include_subworks','Include child subworks','<option value="true">Yes, include automatically</option><option value="false">No</option>')+input('planned_start','Planned start','date')+input('planned_finish','Planned finish','date')+select('responsible_id','Responsible','<option value="">Not assigned</option>'+opts17(state.profiles,'id','full_name')),async d=>{const c=state.moduleRecords.find(x=>x.id===d.catalog_id);if(!c)throw new Error('Select work');await insertPackage17(id,c,d.parent_line_id||null,n17(d.quantity),d,d.include_subworks==='true');await recalcEstimate17(id);await reload17()})};
  async function insertPackage17(estimateId,c,parentId,qty,d,includeChildren){const line=await insert('module_record_lines',{record_id:estimateId,parent_line_id:parentId,line_type:c.record_type==='subwork'?'subwork':'work',code:c.record_number||null,name:c.name,description:c.data?.description||null,quantity:qty,unit:c.data?.unit||'unit',unit_cost:n17(c.cost_amount),unit_sale:n17(c.sale_amount),planned_start:d.planned_start||null,planned_finish:d.planned_finish||null,responsible_id:d.responsible_id||null,status:'draft',sort_order:estimateLines17(estimateId).length+1,data:{catalog_record_id:c.id,hierarchy_kind:c.record_type,default_duration_days:n17(c.data?.default_duration_days),builder:'phase1_7'}}),components=catalogMaterials17(c.id);if(components.length){const payload=components.map((x,i)=>{const m=state.materials.find(y=>y.id===x.material_id),waste=1+n17(x.data?.waste_percent)/100;return {record_id:estimateId,parent_line_id:line.id,line_type:'material',code:m?.code||x.code||null,name:m?.name||x.name,description:x.description||null,material_id:x.material_id,quantity:n17(x.quantity)*qty*waste,unit:x.unit||m?.unit||'pcs',unit_cost:n17(x.unit_cost)||n17(m?.purchase_price),unit_sale:n17(x.unit_sale)||n17(m?.sale_price)||n17(m?.purchase_price),planned_start:d.planned_start||null,planned_finish:d.planned_finish||null,responsible_id:d.responsible_id||null,status:'draft',sort_order:estimateLines17(estimateId).length+i+2,data:{source_catalog_line_id:x.id,waste_percent:n17(x.data?.waste_percent),builder:'phase1_7'}}});await rawApi('/rest/v1/module_record_lines',{method:'POST',headers:{Prefer:'return=representation'},body:JSON.stringify(payload)})}if(includeChildren&&c.record_type==='work_type'){for(const sub of catalogChildren17(c.id).filter(x=>x.record_type==='subwork'))await insertPackage17(estimateId,sub,line.id,qty,d,false)}return line}

  window.addManualEstimateLine17=(id,lineId='')=>{const x=lineId?state.moduleLines.find(y=>y.id===lineId):{},ls=estimateLines17(id),blocked=lineId?descendants17(lineId,ls):new Set(),parents=ls.filter(y=>['section','work','subwork'].includes(y.line_type)&&y.id!==lineId&&!blocked.has(y.id));openModal(lineId?'Изменить строку сметы':'Ручная строка сметы',select('line_type','Type',`<option value="work" ${x.line_type==='work'?'selected':''}>Work</option><option value="subwork" ${x.line_type==='subwork'?'selected':''}>Subwork</option><option value="material" ${x.line_type==='material'?'selected':''}>Material</option>`)+select('parent_line_id','Parent',`<option value="">Top level</option>`+opts17(parents,'id','name',x.parent_line_id||''))+input('code','Code','text',x.code||'')+input('name','Name','text',x.name||'','required')+select('material_id','Material list',materialOptions17(x.material_id))+input('quantity','Quantity','number',x.quantity||1,'step="0.001" min="0"')+select('unit','Unit',unitOptions17(x.unit||'pcs'))+input('unit_cost','Unit cost · AED','number',x.unit_cost||0,'step="0.01"')+input('unit_sale','Unit sale · AED','number',x.unit_sale||0,'step="0.01"')+input('planned_start','Planned start','date',x.planned_start||'')+input('planned_finish','Planned finish','date',x.planned_finish||'')+select('responsible_id','Responsible','<option value="">Not assigned</option>'+opts17(state.profiles,'id','full_name',x.responsible_id||''))+`<label class="full">Description<textarea name="description">${esc(x.description||'')}</textarea></label>`,async d=>{const m=state.materials.find(z=>z.id===d.material_id),rec={record_id:id,parent_line_id:d.parent_line_id||null,line_type:d.line_type,code:d.code||null,name:d.name||m?.name||'Item',description:d.description||null,material_id:d.material_id||null,quantity:n17(d.quantity),unit:d.unit||m?.unit||'pcs',unit_cost:n17(d.unit_cost),unit_sale:n17(d.unit_sale),planned_start:d.planned_start||null,planned_finish:d.planned_finish||null,responsible_id:d.responsible_id||null,status:'draft',sort_order:x.sort_order||ls.length+1,data:{...(x.data||{}),builder:'phase1_7'}};lineId?await update('module_record_lines',lineId,rec):await insert('module_record_lines',rec);await recalcEstimate17(id);await reload17()});setTimeout(()=>bindMaterialFill17(),0)};
  window.editEstimateLine17=(estimateId,lineId)=>{const x=state.moduleLines.find(y=>y.id===lineId);if(x.line_type==='section'){openModal('Изменить раздел',input('name','Section name','text',x.name,'required')+input('code','Code','text',x.code||''),async d=>{await update('module_record_lines',lineId,{name:d.name,code:d.code||null});await reload17()})}else addManualEstimateLine17(estimateId,lineId)};
  window.deleteEstimateLine17=async(estimateId,lineId)=>{const all=estimateLines17(estimateId),x=state.moduleLines.find(y=>y.id===lineId),children=descendants17(lineId,all);if(!confirm(`Удалить «${x?.name}»${children.size?` и ${children.size} вложенных позиций`:''}?`))return;const linked=all.filter(y=>y.id===lineId||children.has(y.id)).map(y=>y.linked_task_id).filter(Boolean);await Promise.all(linked.map(id=>update('tasks',id,{status:'cancelled',updated_at:new Date().toISOString()}).catch(()=>null)));await rawApi(`/rest/v1/module_record_lines?id=eq.${lineId}`,{method:'DELETE'});await recalcEstimate17(estimateId);await reload17();toast('Позиция удалена; связанные задачи отменены')};
  window.syncEstimateExecution17=async id=>{const r=state.moduleRecords.find(x=>x.id===id);if(!['agreed','approved'].includes(r?.status))throw new Error('Сначала утвердите смету');await rawApi('/rest/v1/rpc/activate_estimate_workflow',{method:'POST',body:JSON.stringify({p_estimate_id:id})});await rawApi('/rest/v1/rpc/sync_estimate_execution',{method:'POST',body:JSON.stringify({p_estimate_id:id})});await reload17();openEstimate17(id);toast('Виды работ и подработы переданы в задачи и график')};

  renderPage=function(){if(state.page==='estimates')$('#content').innerHTML=estimateHub17();else baseRender17()};
  actionForPage=function(){if(state.page==='estimates')return state.estimateHubTab==='library'?openWorkCatalog17('work_type'):openEstimateCreate16();return baseAction17()};
  $('#pageAction').onclick=actionForPage;$$('.nav-btn').forEach(b=>b.onclick=()=>setPage(b.dataset.page));
  renderPage();
})();
